import type { ApprovalClaim, ApprovalMutation, ClaimMutation, DraftActor, DraftFields, DraftMutation, DraftRecord, DraftRepository, DraftRevision, DraftScope, SendApproval } from './contracts.js';
import type { SqlClient, SqlRow } from '../activity/postgres-repository.js';

const text = (value: unknown): string => typeof value === 'string' ? value : typeof value === 'number' || typeof value === 'boolean' ? String(value) : ''; 
const stamp = (value: unknown): string => value instanceof Date ? value.toISOString() : text(value);
const fields = (row: SqlRow): DraftFields => ({ recipients: typeof row['recipients'] === 'string' ? JSON.parse(row['recipients']) as DraftFields['recipients'] : row['recipients'] as DraftFields['recipients'], subject: text(row['subject']), body: text(row['body']), bodyFormat: row['body_format'] === 'html' || row['bodyFormat'] === 'html' ? 'html' : 'markdown' });
const draft = (row: SqlRow): DraftRecord => ({ id: text(row['id']), accountId: text(row['account_id']), sourceMessageId: row['source_message_id'] == null ? null : text(row['source_message_id']), createdBy: text(row['created_by']) as DraftActor, state: text(row['state']) as DraftRecord['state'], version: Number(row['version']), createdAt: stamp(row['created_at']), updatedAt: stamp(row['updated_at']), ...fields(row) });
const approval = (row: SqlRow): SendApproval => ({ id: text(row['id']), draftId: text(row['draft_id']), draftVersion: Number(row['draft_version']), userId: text(row['user_id']), confirmationHash: text(row['confirmation_hash']), idempotencyKey: text(row['idempotency_key']), expiresAt: stamp(row['expires_at']) });
const audit = (sql: SqlClient, scope: DraftScope, accountId: string, event: string, metadata: Record<string, unknown>) => { const draftId = metadata['draftId']; return sql.query(`INSERT INTO app.audits (actor_type, actor_id, account_id, activity_id, event, correlation_id, metadata) VALUES ('user', $1, $2::uuid, NULL, $3, $4, $5::jsonb)`, [scope.subjectId, accountId, event, `draft:${typeof draftId === 'string' ? draftId : ''}`, JSON.stringify(metadata)]); };

/** PostgreSQL repository: claim transactions are intentionally short; provider I/O lives in DraftService. */
export class PostgresDraftRepository implements DraftRepository {
  constructor(private readonly sql: SqlClient) {}
  async create(scope: DraftScope, input: Omit<DraftRecord, 'id' | 'version' | 'createdAt' | 'updatedAt'>): Promise<DraftRecord> { return this.sql.transaction(async (sql) => { const result = await sql.query(`INSERT INTO app.drafts (account_id, source_message_id, created_by, state, recipients, subject, body, body_format) VALUES ($1::uuid, $2::uuid, $3, $4, $5::jsonb, $6, $7, $8) RETURNING *`, [input.accountId, input.sourceMessageId ?? null, input.createdBy, input.state, JSON.stringify(input.recipients), input.subject, input.body, input.bodyFormat]); const row = result.rows[0]; if (!row) throw new Error('Draft insert failed.'); const value = draft(row); await sql.query(`INSERT INTO app.draft_revisions (draft_id, version, editor, snapshot) VALUES ($1::uuid, 1, $2, $3::jsonb)`, [value.id, input.createdBy, JSON.stringify(fields(value))]); await audit(sql, scope, value.accountId, 'draft.created', { draftId: value.id, version: 1, editor: input.createdBy }); return value; }); }
  async get(scope: DraftScope, id: string): Promise<DraftRecord | null> { const result = await this.sql.query(`SELECT * FROM app.drafts WHERE id = $1::uuid AND account_id = ANY($2::uuid[])`, [id, scope.accountIds]); return result.rows[0] ? draft(result.rows[0]) : null; }
  async edit(scope: DraftScope, id: string, expected: number, input: DraftFields, editor: DraftActor): Promise<DraftMutation> { return this.sql.transaction(async (sql) => { const current = await this.lock(sql, scope, id); if (!current) return { kind: 'not_found' }; if (current.version !== expected) return { kind: 'conflict', currentVersion: current.version }; if (current.state !== 'editing' && current.state !== 'failed') return { kind: 'blocked', reason: 'Only editable drafts can be changed.' }; const update = await sql.query(`UPDATE app.drafts SET recipients = $1::jsonb, subject = $2, body = $3, body_format = $4, state = 'editing', version = version + 1, updated_at = now() WHERE id = $5::uuid AND version = $6 RETURNING *`, [JSON.stringify(input.recipients), input.subject, input.body, input.bodyFormat, id, expected]); if (!update.rows[0]) return { kind: 'conflict', currentVersion: expected + 1 }; const value = draft(update.rows[0]); await sql.query(`INSERT INTO app.draft_revisions (draft_id, version, editor, snapshot) VALUES ($1::uuid, $2, $3, $4::jsonb)`, [id, value.version, editor, JSON.stringify(fields(value))]); await audit(sql, scope, value.accountId, 'draft.edited', { draftId: id, version: value.version, editor }); return { kind: 'updated', draft: value }; }); }
  async history(scope: DraftScope, id: string): Promise<readonly DraftRevision[] | null> { const current = await this.get(scope, id); if (!current) return null; const result = await this.sql.query(`SELECT draft_id, version, editor, snapshot, created_at FROM app.draft_revisions WHERE draft_id = $1::uuid ORDER BY version`, [id]); return result.rows.map((row) => { const raw = typeof row['snapshot'] === 'string' ? JSON.parse(row['snapshot']) as Record<string, unknown> : row['snapshot'] as Record<string, unknown>; const snapshot = { ...raw, bodyFormat: raw['bodyFormat'] === 'html' ? 'html' : 'markdown' } as DraftFields; return { draftId: text(row['draft_id']), version: Number(row['version']), editor: text(row['editor']) as DraftActor, snapshot, createdAt: stamp(row['created_at']) }; }); }
  async createApproval(scope: DraftScope, id: string, expected: number, confirmationHash: string, expiresAt: string, idempotencyKey: string): Promise<ApprovalMutation> { return this.sql.transaction(async (sql) => { const current = await this.lock(sql, scope, id); if (!current) return { kind: 'not_found' }; if (current.version !== expected) return { kind: 'conflict', currentVersion: current.version }; if (current.state !== 'editing' && current.state !== 'failed') return { kind: 'blocked', reason: 'Only editable drafts can be approved.' }; const publicRequest = await sql.query(`SELECT id FROM app.public_mcp_send_requests WHERE user_id = $1::uuid AND draft_id = $2::uuid AND draft_version = $3 AND state IN ('pending_owner_approval','sending','unverifiable') LIMIT 1`, [scope.subjectId, id, expected]); if (publicRequest.rows[0]) return { kind: 'blocked', reason: 'This agent draft has an owner send request; use that approval flow.' }; const approvalId = idempotencyKey.split(':')[1]; if (!approvalId) throw new Error('Invalid deterministic approval key.'); const result = await sql.query(`INSERT INTO app.send_approvals (id, draft_id, draft_version, user_id, confirmation_hash, idempotency_key, expires_at) VALUES ($1::uuid, $2::uuid, $3, $4::uuid, $5, $6, $7::timestamptz) RETURNING *`, [approvalId, id, expected, scope.subjectId, confirmationHash, idempotencyKey, expiresAt]); const row = result.rows[0]; if (!row) throw new Error('Approval insert failed.'); await audit(sql, scope, current.accountId, 'send.approved', { draftId: id, approvalId, version: expected }); return { kind: 'created', approval: approval(row) }; }); }
  async claimApproval(scope: DraftScope, id: string, confirmationHash: string, now: string): Promise<ClaimMutation> { return this.sql.transaction(async (sql) => { const result = await sql.query(`SELECT sa.id AS approval_id, sa.draft_id AS approval_draft_id, sa.draft_version AS approval_draft_version, sa.user_id AS approval_user_id, sa.confirmation_hash AS approval_confirmation_hash, sa.idempotency_key AS approval_idempotency_key, sa.expires_at AS approval_expires_at, sa.state AS approval_state, sa.consumed_at AS approval_consumed_at, d.* FROM app.send_approvals sa JOIN app.drafts d ON d.id = sa.draft_id WHERE sa.id = $1::uuid AND sa.user_id = $2::uuid AND d.account_id = ANY($3::uuid[]) FOR UPDATE OF sa, d`, [id, scope.subjectId, scope.accountIds]); const row = result.rows[0]; if (!row) return { kind: 'not_found' }; const current = draft(row); const approved: SendApproval = { id: text(row['approval_id']), draftId: text(row['approval_draft_id']), draftVersion: Number(row['approval_draft_version']), userId: text(row['approval_user_id']), confirmationHash: text(row['approval_confirmation_hash']), idempotencyKey: text(row['approval_idempotency_key']), expiresAt: stamp(row['approval_expires_at']) }; if (row['approval_consumed_at'] != null || approved.confirmationHash !== confirmationHash || approved.expiresAt <= now || current.version !== approved.draftVersion || (current.state !== 'editing' && current.state !== 'failed')) return { kind: 'rejected', reason: 'This confirmation is stale or invalid.' }; await sql.query(`UPDATE app.send_approvals SET state = 'consumed', consumed_at = $1::timestamptz WHERE id = $2::uuid`, [now, id]); await sql.query(`UPDATE app.drafts SET state = 'sending', updated_at = $1::timestamptz WHERE id = $2::uuid`, [now, current.id]); await audit(sql, scope, current.accountId, 'send.claimed', { draftId: current.id, approvalId: id, version: current.version }); return { kind: 'claimed', claim: { approval: approved, draft: current } }; }); }
  async completeSend(scope: DraftScope, claim: ApprovalClaim, outcome: 'sent' | 'failed', providerMessageId?: string): Promise<DraftRecord> { return this.sql.transaction(async (sql) => { const state = outcome === 'sent' ? 'sent' : 'failed'; const result = await sql.query(`UPDATE app.drafts SET state = $1::app.draft_state, version = version + 1, updated_at = now() WHERE id = $2::uuid AND account_id = ANY($3::uuid[]) AND state = 'sending' RETURNING *`, [state, claim.draft.id, scope.accountIds]); const row = result.rows[0]; if (!row) throw new Error('Send completion lost its draft.'); const value = draft(row); await audit(sql, scope, value.accountId, outcome === 'sent' ? 'send.sent' : 'send.failed', { draftId: value.id, approvalId: claim.approval.id, version: claim.draft.version, ...(providerMessageId ? { providerMessageId } : {}) }); return value; }); }
  private async lock(sql: SqlClient, scope: DraftScope, id: string): Promise<DraftRecord | null> { const result = await sql.query(`SELECT * FROM app.drafts WHERE id = $1::uuid AND account_id = ANY($2::uuid[]) FOR UPDATE`, [id, scope.accountIds]); return result.rows[0] ? draft(result.rows[0]) : null; }
}
