import type { DraftFields } from '@hypermail/contracts';
import type { ApprovalClaim, ApprovalMutation, ClaimMutation, DraftActor, DraftMutation, DraftRecord, DraftRepository, DraftRevision, DraftScope, SendApproval } from './contracts.js';
import { createDraftInTransaction, editDraftInTransaction, enqueueMailboxMemoryEventInTransaction } from '@hypermail/db';
import { insertApprovedSubmission, submissionView, lockRecentSendSession } from '@hypermail/send';
import { DraftConflictError, DraftNotFoundError, DraftBlockedError, FreshAuthRequiredError } from './contracts.js';
import type { SqlClient, SqlRow } from '../activity/postgres-repository.js';

const text = (value: unknown): string => typeof value === 'string' ? value : typeof value === 'number' || typeof value === 'boolean' ? String(value) : ''; 
const stamp = (value: unknown): string => value instanceof Date ? value.toISOString() : text(value);
const fields = (row: SqlRow): DraftFields => ({ recipients: typeof row['recipients'] === 'string' ? JSON.parse(row['recipients']) as DraftFields['recipients'] : row['recipients'] as DraftFields['recipients'], subject: text(row['subject']), body: text(row['body']), bodyFormat: row['body_format'] === 'html' || row['bodyFormat'] === 'html' ? 'html' : 'markdown' });
const draft = (row: SqlRow): DraftRecord => ({ id: text(row['id']), accountId: text(row['account_id']), sourceMessageId: row['source_message_id'] == null ? null : text(row['source_message_id']), createdBy: text(row['created_by']) as DraftActor, state: text(row['state']) as DraftRecord['state'], version: Number(row['version']), createdAt: stamp(row['created_at']), updatedAt: stamp(row['updated_at']), ...fields(row) });
const approval = (row: SqlRow): SendApproval => ({ id: text(row['id']), draftId: text(row['draft_id']), draftVersion: Number(row['draft_version']), userId: text(row['user_id']), confirmationHash: text(row['confirmation_hash']), idempotencyKey: text(row['idempotency_key']), expiresAt: stamp(row['expires_at']) });
const audit = (sql: SqlClient, scope: DraftScope, accountId: string, event: string, metadata: Record<string, unknown>) => { const draftId = metadata['draftId']; return sql.query(`INSERT INTO app.audits (actor_type, actor_id, account_id, activity_id, event, correlation_id, metadata) VALUES ('user', $1, $2::uuid, NULL, $3, $4, $5::jsonb)`, [scope.subjectId, accountId, event, `draft:${typeof draftId === 'string' ? draftId : ''}`, JSON.stringify(metadata)]); };

/** PostgreSQL repository: claim transactions are intentionally short; provider I/O lives in DraftService. */
export class PostgresDraftRepository implements DraftRepository {
  constructor(private readonly sql: SqlClient) {}
  async create(scope: DraftScope, input: Omit<DraftRecord, 'id' | 'version' | 'createdAt' | 'updatedAt'>): Promise<DraftRecord> { return this.sql.transaction(async sql => await createDraftInTransaction(sql,scope.subjectId,input) as DraftRecord); }
  async get(scope: DraftScope, id: string): Promise<DraftRecord | null> { const result = await this.sql.query(`SELECT d.* FROM app.drafts d JOIN app.user_accounts ua ON ua.account_id=d.account_id WHERE d.id = $1::uuid AND d.account_id = ANY($2::uuid[]) AND ua.user_id=$3::uuid`, [id, scope.accountIds,scope.subjectId]); return result.rows[0] ? {...draft(result.rows[0]),submission:await submissionView(this.sql,scope.subjectId,id)} : null; }
  async edit(scope: DraftScope, id: string, expected: number, input: DraftFields, editor: DraftActor): Promise<DraftMutation> { return this.sql.transaction(async sql => await editDraftInTransaction(sql,{userId:scope.subjectId,accountIds:scope.accountIds},id,expected,input,editor) as DraftMutation); }
  async history(scope: DraftScope, id: string): Promise<readonly DraftRevision[] | null> { const current = await this.get(scope, id); if (!current) return null; const result = await this.sql.query(`SELECT draft_id, version, editor, snapshot, created_at FROM app.draft_revisions WHERE draft_id = $1::uuid ORDER BY version`, [id]); return result.rows.map((row) => { const raw = typeof row['snapshot'] === 'string' ? JSON.parse(row['snapshot']) as Record<string, unknown> : row['snapshot'] as Record<string, unknown>; const snapshot = { ...raw, bodyFormat: raw['bodyFormat'] === 'html' ? 'html' : 'markdown' } as DraftFields; return { draftId: text(row['draft_id']), version: Number(row['version']), editor: text(row['editor']) as DraftActor, snapshot, createdAt: stamp(row['created_at']) }; }); }
  async createApproval(scope: DraftScope, id: string, expected: number, confirmationHash: string, expiresAt: string, idempotencyKey: string): Promise<ApprovalMutation> { return this.sql.transaction(async (sql) => { const current = await this.lock(sql, scope, id); if (!current) return { kind: 'not_found' }; if (current.version !== expected) return { kind: 'conflict', currentVersion: current.version }; if (current.state !== 'editing' && current.state !== 'failed') return { kind: 'blocked', reason: 'Only editable drafts can be approved.' }; const publicRequest = await sql.query(`SELECT id FROM app.public_mcp_send_requests WHERE user_id = $1::uuid AND draft_id = $2::uuid AND draft_version = $3 AND state IN ('pending_owner_approval','sending','unverifiable') LIMIT 1`, [scope.subjectId, id, expected]); if (publicRequest.rows[0]) return { kind: 'blocked', reason: 'This agent draft has an owner send request; use that approval flow.' }; const approvalId = idempotencyKey.split(':')[1]; if (!approvalId) throw new Error('Invalid deterministic approval key.'); const result = await sql.query(`INSERT INTO app.send_approvals (id, draft_id, draft_version, user_id, confirmation_hash, idempotency_key, expires_at) VALUES ($1::uuid, $2::uuid, $3, $4::uuid, $5, $6, $7::timestamptz) RETURNING *`, [approvalId, id, expected, scope.subjectId, confirmationHash, idempotencyKey, expiresAt]); const row = result.rows[0]; if (!row) throw new Error('Approval insert failed.'); await audit(sql, scope, current.accountId, 'send.approved', { draftId: id, approvalId, version: expected }); return { kind: 'created', approval: approval(row) }; }); }
  async claimApproval(scope:DraftScope,id:string,confirmationHash:string,now:string):Promise<ClaimMutation>{
    return this.sql.transaction(async sql=>{
      if(!await lockRecentSendSession(sql,scope))throw new FreshAuthRequiredError();
      const row=(await sql.query(`SELECT sa.*,d.id draft_identity FROM app.send_approvals sa JOIN app.drafts d ON d.id=sa.draft_id JOIN app.user_accounts ua ON ua.account_id=d.account_id WHERE sa.id=$1::uuid AND sa.user_id=$2::uuid AND ua.user_id=$2::uuid AND d.account_id=ANY($3::uuid[]) FOR UPDATE OF sa,d`,[id,scope.subjectId,scope.accountIds])).rows[0];
      if(!row)return {kind:'not_found'};
      const current=await this.lock(sql,scope,text(row['draft_id']));if(!current)return {kind:'not_found'};
      const approved=approval(row);
      if(row['state']!=='pending'||row['consumed_at']!=null||approved.confirmationHash!==confirmationHash||approved.expiresAt<=now||current.version!==approved.draftVersion||!['editing','failed'].includes(current.state))return {kind:'rejected',reason:'This confirmation is stale or invalid.'};
      await insertApprovedSubmission(sql,scope.subjectId,'draft',current.id,{approvalId:id,accountId:current.accountId,draftId:current.id,draftVersion:current.version,idempotencyKey:approved.idempotencyKey,recipients:current.recipients,subject:current.subject,body:current.body,bodyFormat:current.bodyFormat,sourceMessageId:current.sourceMessageId});
      await sql.query(`UPDATE app.send_approvals SET state='consumed',consumed_at=$2::timestamptz WHERE id=$1::uuid`,[id,now]);
      await sql.query(`UPDATE app.drafts SET state='sending',updated_at=$2::timestamptz WHERE id=$1::uuid`,[current.id,now]);
      await audit(sql,scope,current.accountId,'send.claimed',{draftId:current.id,approvalId:id,version:current.version});
      await enqueueMailboxMemoryEventInTransaction(sql,{userId:scope.subjectId,mailboxId:current.accountId,sourceType:'send_approval',sourceId:id,sourceVersion:current.version,kind:'send_owner_confirmed',occurredAt:now,contentPayload:{outcome:'confirmed',draftId:current.id,draftVersion:current.version,draftCreator:current.createdBy}});
      return {kind:'claimed',claim:{approval:approved,draft:current}};
    });
  }
  async completeSend(scope:DraftScope,claim:ApprovalClaim,outcome:'sent'|'failed',providerMessageId?:string):Promise<DraftRecord>{
    await this.sql.transaction(async sql=>{
      const current=await this.lock(sql,scope,claim.draft.id);if(!current)throw new DraftNotFoundError();
      if(current.state===outcome)return;
      if(current.state!=='sending'||current.version!==claim.draft.version)throw new DraftConflictError();
      const journal=(await sql.query(`SELECT state FROM app.approved_send_submissions WHERE approval_id=$1::uuid AND user_id=$2::uuid AND source_kind='draft' AND source_id=$3::uuid AND source_version=$4`,[claim.approval.id,scope.subjectId,current.id,claim.approval.draftVersion])).rows[0];
      if(journal?.['state']!==(outcome==='sent'?'verified':'rejected'))throw new DraftBlockedError('Provider outcome has no durable submission proof.');
      const row=(await sql.query(`UPDATE app.drafts SET state=$1::app.draft_state,version=version+1,updated_at=now() WHERE id=$2::uuid AND version=$3 AND state='sending' RETURNING *`,[outcome,current.id,current.version])).rows[0];if(!row)throw new DraftConflictError();const value=draft(row);
      await audit(sql,scope,current.accountId,outcome==='sent'?'send.sent':'send.failed',{draftId:current.id,approvalId:claim.approval.id,version:claim.approval.draftVersion,providerMessageId:providerMessageId??null});
      await enqueueMailboxMemoryEventInTransaction(sql,{userId:scope.subjectId,mailboxId:current.accountId,sourceType:'send_approval',sourceId:claim.approval.id,sourceVersion:claim.approval.draftVersion,kind:outcome==='sent'?'send_verified':'send_failed',occurredAt:value.updatedAt,contentPayload:{outcome:outcome==='sent'?'verified_sent':'failed',draftId:current.id,draftVersion:claim.approval.draftVersion}});
    });
    const value=await this.get(scope,claim.draft.id);if(!value)throw new DraftNotFoundError();return value;
  }
  async reconcileClaim(scope:DraftScope,id:string,approvalId:string,expected:number):Promise<ApprovalClaim>{return this.sql.transaction(async sql=>{const current=await this.lock(sql,scope,id);if(!current)throw new DraftNotFoundError();if(current.version!==expected)throw new DraftConflictError();const row=(await sql.query(`SELECT a.* FROM app.send_approvals a JOIN app.approved_send_submissions s ON s.approval_id=a.id WHERE a.id=$1::uuid AND a.user_id=$2::uuid AND a.draft_id=$3::uuid AND s.source_kind='draft' AND s.source_id=$3::uuid`,[approvalId,scope.subjectId,id])).rows[0];if(!row)throw new DraftNotFoundError();return {approval:approval(row),draft:current};});}
  async manualReview(scope:DraftScope,id:string,approvalId:string,expected:number,outcome:'observed_sent'|'not_observed',note:string):Promise<DraftRecord>{await this.sql.transaction(async sql=>{const current=await this.lock(sql,scope,id);if(!current)throw new DraftNotFoundError();if(current.version!==expected)throw new DraftConflictError();const row=(await sql.query(`SELECT approval_id FROM app.approved_send_submissions WHERE approval_id=$1::uuid AND user_id=$2::uuid AND source_kind='draft' AND source_id=$3::uuid AND state IN ('unknown','reported') FOR UPDATE`,[approvalId,scope.subjectId,id])).rows[0];if(!row)throw new DraftBlockedError('Only an ambiguous submission can be manually reviewed.');await sql.query(`INSERT INTO app.approved_send_manual_reviews(approval_id,user_id,account_id,outcome,note) VALUES($1::uuid,$2::uuid,$3::uuid,$4,$5)`,[approvalId,scope.subjectId,current.accountId,outcome,note]);await audit(sql,scope,current.accountId,'send.manual_review',{draftId:id,approvalId,outcome});});const value=await this.get(scope,id);if(!value)throw new DraftNotFoundError();return value;}
  private async lock(sql: SqlClient, scope: DraftScope, id: string): Promise<DraftRecord | null> { const result = await sql.query(`SELECT d.* FROM app.drafts d JOIN app.user_accounts ua ON ua.account_id=d.account_id WHERE d.id = $1::uuid AND d.account_id = ANY($2::uuid[]) AND ua.user_id=$3::uuid FOR UPDATE OF d`, [id, scope.accountIds,scope.subjectId]); return result.rows[0] ? draft(result.rows[0]) : null; }
}
