import { describe, expect, it } from 'vitest';
import { agentTaskBackoffMs, agentTaskOutboxEnvelopeSchema, agentTaskResultSchema, agentTaskSchema, answerAgentTaskQuestion, claimAgentTask, classifyAgentTaskIdempotency, expireAgentTaskLease, heartbeatAgentTask, isRetryableAgentTaskError, obsoleteAgentTask, reportAgentTaskFailure, reportAgentTaskResult, resumeObsoleteAgentTask, type AgentTask } from '../src/index.js';
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const d=(c='a')=>c.repeat(64); const t0='2026-08-10T12:00:00.000Z',t1='2026-08-10T12:01:00.000Z',t2='2026-08-10T12:02:00.000Z',t3='2026-08-10T12:03:00.000Z',deadline='2026-08-10T13:00:00.000Z';
const base=(o:Partial<AgentTask>={}):AgentTask=>agentTaskSchema.parse({id:id(1),activityId:id(2),userId:id(3),mailboxId:id(4),manager:{kind:'agent_connection',connectionId:id(5)},managerLifecycleRevision:2,assignmentId:id(6),assignmentRevision:2,grantId:id(7),grantRevision:3,safetyRevision:1,state:'pending',pendingReason:'initial',version:1,attemptCount:0,maxAttempts:2,leaseGeneration:0,lease:null,currentRunId:null,result:null,lastErrorCode:null,availableAt:t0,deadlineAt:deadline,createdAt:t0,updatedAt:t0,completedAt:null,obsoleteAt:null,...o});
const claim=(task:AgentTask)=>claimAgentTask(task,{taskId:task.id,requestId:'request-claim-0001',requestDigest:d(),expectedVersion:task.version,occurredAt:t1,runId:id(8),claimedBy:'worker-1',leaseTokenDigest:d('b'),leaseExpiresAt:t2});
const report=(task:AgentTask,result:unknown,owned:string[]=[])=>reportAgentTaskResult(task,{taskId:task.id,requestId:'request-report-001',requestDigest:d('c'),expectedVersion:task.version,occurredAt:'2026-08-10T12:01:30.000Z',leaseGeneration:task.leaseGeneration,leaseTokenDigest:d('b'),result} as never,owned);
describe('agent Task contract',()=>{
 it('is strict, target-only, and excludes fallback/success result vocabulary',()=>{ expect(()=>base({manager:{kind:'none'} as never})).toThrow(); expect(()=>agentTaskSchema.parse({...base(),body:'secret'})).toThrow(); expect(()=>agentTaskResultSchema.parse({kind:'success'})).toThrow(); expect(()=>agentTaskResultSchema.parse({kind:'fallback'})).toThrow(); });
 it('claims with immutable Run and monotonically fenced lease generation',()=>{const leased=claim(base()); expect(leased).toMatchObject({state:'leased',attemptCount:1,leaseGeneration:1,currentRunId:id(8)}); expect(base().state).toBe('pending'); expect(()=>claim(leased)).toThrow(/pending/); expect(()=>heartbeatAgentTask(leased,{taskId:leased.id,requestId:'request-heartbeat1',requestDigest:d(),expectedVersion:leased.version,occurredAt:t1,leaseGeneration:2,leaseTokenDigest:d('b'),leaseExpiresAt:t3})).toThrow(/Stale lease/);});
 it('accepts heartbeat and rejects expired/stale reports',()=>{const leased=claim(base()); const beat=heartbeatAgentTask(leased,{taskId:leased.id,requestId:'request-heartbeat1',requestDigest:d(),expectedVersion:leased.version,occurredAt:t1,leaseGeneration:1,leaseTokenDigest:d('b'),leaseExpiresAt:t3}); expect(beat.lease?.heartbeatAt).toBe(t1); expect(()=>reportAgentTaskResult(beat,{taskId:beat.id,requestId:'request-report-001',requestDigest:d(),expectedVersion:beat.version,occurredAt:'2026-08-10T12:04:00.000Z',leaseGeneration:1,leaseTokenDigest:d('b'),result:{kind:'no_action'}})).toThrow(/expired/);});
 it('models every result destination and enforces Action ownership',()=>{expect(report(claim(base()),{kind:'no_action'}).state).toBe('completed'); expect(report(claim(base()),{kind:'question',questionId:id(9)}).state).toBe('waiting_for_answer'); const l=claim(base()); expect(()=>report(l,{kind:'action_requests_emitted',actionIds:[id(10)]})).toThrow(/belong/); expect(report(l,{kind:'action_requests_emitted',actionIds:[id(10)]},[id(10)]).state).toBe('awaiting_action_verification');});
 it('appends an answer as a continuation and requires matching question',()=>{const q=report(claim(base()),{kind:'question',questionId:id(9)}); const command={taskId:q.id,requestId:'request-answer-0001',requestDigest:d(),expectedVersion:q.version,occurredAt:t2,questionId:id(9),answerDigest:d('d'),continuationRunId:id(11)}; expect(answerAgentTaskQuestion(q,command)).toMatchObject({state:'pending',pendingReason:'continuation',result:null}); expect(()=>answerAgentTaskQuestion(q,{...command,questionId:id(12)})).toThrow();});
 it('retries same Task then dead-letters at max attempts',()=>{let l=claim(base()); const retry=reportAgentTaskFailure(l,{taskId:l.id,requestId:'request-failure-001',requestDigest:d(),expectedVersion:l.version,occurredAt:t1,leaseGeneration:1,leaseTokenDigest:d('b'),errorCode:'RATE_LIMITED'},t2); expect(retry).toMatchObject({id:id(1),state:'pending',pendingReason:'retry'}); l=claimAgentTask(retry,{taskId:retry.id,requestId:'request-claim-0002',requestDigest:d(),expectedVersion:retry.version,occurredAt:t2,runId:id(12),claimedBy:'worker',leaseTokenDigest:d('e'),leaseExpiresAt:t3}); const dead=reportAgentTaskFailure(l,{taskId:l.id,requestId:'request-failure-002',requestDigest:d(),expectedVersion:l.version,occurredAt:t2,leaseGeneration:2,leaseTokenDigest:d('e'),errorCode:'RATE_LIMITED'},t3); expect(dead.state).toBe('dead_letter');});
 it('expires leases, obsoletes reassignment, and requires explicit new owner resume',()=>{const expired=expireAgentTaskLease(claim(base()),t3,'2026-08-10T12:04:00.000Z'); expect(expired.state).toBe('pending'); const old=obsoleteAgentTask(base(),t1); const replacement=base({id:id(20),manager:{kind:'mastra'},managerLifecycleRevision:null,pendingReason:'owner_resumed'}); expect(resumeObsoleteAgentTask(old,replacement)).toStrictEqual(replacement); expect(()=>resumeObsoleteAgentTask(old,base({pendingReason:'owner_resumed'}))).toThrow();});
 it('accepts a privacy-minimized result only for a completed Task',()=>{const completed=report(claim(base()),{kind:'no_action'});expect(agentTaskSchema.parse({...completed,result:{kind:'redacted'}}).result).toEqual({kind:'redacted'});expect(()=>base({result:{kind:'redacted'} as never})).toThrow();});
 it('has deterministic idempotency and backoff classifiers',()=>{expect(classifyAgentTaskIdempotency(undefined,'request-id-00001',d())).toBe('new'); expect(classifyAgentTaskIdempotency({requestId:'request-id-00001',requestDigest:d()},'request-id-00001',d())).toBe('replay'); expect(classifyAgentTaskIdempotency({requestId:'request-id-00001',requestDigest:d()},'request-id-00001',d('b'))).toBe('mismatch'); expect(isRetryableAgentTaskError('RATE_LIMITED')).toBe(true); expect(isRetryableAgentTaskError('AUTHORIZATION_REVOKED')).toBe(false); expect(agentTaskBackoffMs(3)).toBe(4000);});
 it('keeps outbox privacy-safe and validates temporal invariants',()=>{const envelope={id:id(30),taskId:id(1),activityId:id(2),mailboxId:id(4),event:'task_available',taskVersion:1,payloadDigest:d(),correlationId:'correlation-1',occurredAt:t0}; expect(agentTaskOutboxEnvelopeSchema.parse(envelope)).toEqual(envelope); expect(()=>agentTaskOutboxEnvelopeSchema.parse({...envelope,accountEmail:'x@y.com'})).toThrow(); expect(()=>base({deadlineAt:'2026-08-10T11:00:00.000Z'})).toThrow();});
});
