import { createHash, randomBytes, randomUUID } from 'node:crypto';
import {
  agentTaskSchema, agentTaskBackoffMs, answerAgentTaskQuestion, cancelAgentTask, claimAgentTask, completeAgentTaskActionVerification, expireAgentTaskLease,
  heartbeatAgentTask, reportAgentTaskFailure, reportAgentTaskResult,
  type AgentTask, type AgentTaskErrorCode, type AgentTaskResult,
} from '@hypermail/contracts';
import type { SqlClient } from './postgres-client.js';

const iso=(v:Date|string):string=>v instanceof Date?v.toISOString():v;
const digest=(v:string):string=>createHash('sha256').update(v).digest('hex');
const jsonDigest=(v:unknown):string=>digest(JSON.stringify(v));
type TaskRow=Record<string,unknown>;
const taskFrom=(r:TaskRow):AgentTask=>agentTaskSchema.parse({
 id:r['id'],activityId:r['activity_id'],userId:r['user_id'],mailboxId:r['account_id'],manager:r['manager_kind']==='agent_connection'?{kind:'agent_connection',connectionId:r['manager_connection_id']}:{kind:'mastra'},managerLifecycleRevision:r['manager_lifecycle_revision'],assignmentId:r['assignment_id'],assignmentRevision:r['assignment_revision'],grantId:r['grant_id'],grantRevision:r['grant_revision'],safetyRevision:r['safety_revision'],state:r['state'],pendingReason:r['pending_reason'],version:r['version'],attemptCount:r['attempt_count'],maxAttempts:r['max_attempts'],leaseGeneration:r['lease_generation'],lease:r['lease_token_digest']==null?null:{generation:r['lease_generation'],tokenDigest:r['lease_token_digest'],claimedBy:r['lease_claimed_by'],claimedAt:iso(r['lease_claimed_at'] as Date|string),heartbeatAt:iso(r['lease_heartbeat_at'] as Date|string),expiresAt:iso(r['lease_expires_at'] as Date|string)},currentRunId:r['current_run_id'],result:r['result'],lastErrorCode:r['last_error_code'],availableAt:iso(r['available_at'] as Date|string),deadlineAt:iso(r['deadline_at'] as Date|string),createdAt:iso(r['created_at'] as Date|string),updatedAt:iso(r['updated_at'] as Date|string),completedAt:r['completed_at']==null?null:iso(r['completed_at'] as Date|string),obsoleteAt:r['obsolete_at']==null?null:iso(r['obsolete_at'] as Date|string),
});
const one=<T>(rows:readonly T[],message:string):T=>{const row=rows[0];if(!row)throw new Error(message);return row;};
export type EnqueueAgentTask=Readonly<{task:AgentTask;enqueueKey:string;inputDigest:string;correlationId:string}>;
export type ClaimedAgentTask=Readonly<{task:AgentTask;runId:string;leaseToken:string}>;
export type TaskTarget={kind:'mastra'}|{kind:'agent_connection';connectionId:string};
export interface AgentTaskAdmission { authorizeTask(userId:string,at:Date):Promise<Readonly<{allowed:boolean;reason?:string}>>; }

/** Transactional source of truth for durable automatic work. Queue transports are only wake-ups. */
export class AgentTaskStore {
 constructor(private readonly sql:SqlClient,private readonly admission?:AgentTaskAdmission){}
 async enqueue(input:EnqueueAgentTask):Promise<AgentTask>{
  const t=agentTaskSchema.parse(input.task);if(this.admission&&!((await this.admission.authorizeTask(t.userId,new Date(t.createdAt))).allowed))throw new Error('TASK_ADMISSION_DENIED'); if(t.state!=='pending'||t.attemptCount!==0||t.leaseGeneration!==0)throw new Error('New Task must be initially pending.');
  return this.sql.transaction(async db=>{
   const m=t.manager.kind==='agent_connection'?[t.manager.kind,t.manager.connectionId]:['mastra',null];
   const inserted=await db.query<TaskRow>(`insert into app.agent_tasks(id,enqueue_key,activity_id,user_id,account_id,manager_kind,manager_connection_id,manager_lifecycle_revision,assignment_id,assignment_revision,grant_id,grant_revision,safety_revision,state,pending_reason,version,attempt_count,max_attempts,lease_generation,result,last_error_code,available_at,deadline_at,created_at,updated_at,completed_at,obsolete_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20::jsonb,$21,$22::timestamptz,$23::timestamptz,$24::timestamptz,$25::timestamptz,$26::timestamptz,$27::timestamptz) on conflict(enqueue_key) do nothing returning *`,[t.id,input.enqueueKey,t.activityId,t.userId,t.mailboxId,...m,t.managerLifecycleRevision,t.assignmentId,t.assignmentRevision,t.grantId,t.grantRevision,t.safetyRevision,t.state,t.pendingReason,t.version,t.attemptCount,t.maxAttempts,t.leaseGeneration,t.result,t.lastErrorCode,t.availableAt,t.deadlineAt,t.createdAt,t.updatedAt,t.completedAt,t.obsoleteAt]);
   const actual=taskFrom(inserted.rows[0]??one((await db.query<TaskRow>('select * from app.agent_tasks where enqueue_key=$1 for update',[input.enqueueKey])).rows,'Task enqueue conflict disappeared.'));
   if(actual.id!==t.id||actual.activityId!==t.activityId||jsonDigest(actual.manager)!==jsonDigest(t.manager))throw new Error('Task enqueue idempotency conflict.');
   await this.outbox(db,actual,'task_available',input.inputDigest,input.correlationId,actual.createdAt);
   return actual;
  });
 }
 /** Exact-target claim. No query can select another Manager kind or connection. */
 async claim(target:TaskTarget,claimedBy:string,now:string,leaseMs=60_000):Promise<ClaimedAgentTask|null>{return this.sql.transaction(async db=>{
  const connection=target.kind==='agent_connection'?target.connectionId:null;
  const rows=await db.query<TaskRow>(`select t.* from app.agent_tasks t where t.state='pending' and t.available_at<=$3::timestamptz and t.deadline_at>$3::timestamptz and t.manager_kind=$1 and t.manager_connection_id is not distinct from $2::uuid and t.attempt_count<t.max_attempts and ${this.authoritySql('t')} order by t.available_at,t.created_at for update of t skip locked limit 1`,[target.kind,connection,now]);
  const current=rows.rows[0]?taskFrom(rows.rows[0]):null;if(!current)return null;
  if(this.admission&&!((await this.admission.authorizeTask(current.userId,new Date(now))).allowed))return null;
  const continuation=current.pendingReason==='continuation'?(await db.query<{id:string}>(`select id from app.agent_runs where activity_id=$1 and state='created' and trigger->>'kind'='question_answer' and trigger->>'taskId'=$2 order by sequence desc limit 1 for update`,[current.activityId,current.id])).rows[0]:undefined;
  const raw=randomBytes(32).toString('base64url'),tokenDigest=digest(raw),runId=continuation?.id??randomUUID(),requestId=`claim:${runId}`,at=new Date(now),expires=new Date(Math.min(at.valueOf()+leaseMs,new Date(current.deadlineAt).valueOf())).toISOString();
  const next=claimAgentTask(current,{taskId:current.id,requestId,requestDigest:digest(requestId),expectedVersion:current.version,occurredAt:now,runId,claimedBy,leaseTokenDigest:tokenDigest,leaseExpiresAt:expires});
  if(continuation)await db.query(`update app.agent_runs set state='running',started_at=$2::timestamptz where id=$1 and state='created'`,[runId,now]);
  else {const seq=one((await db.query<{sequence:number}>('select coalesce(max(sequence),0)::integer+1 as sequence from app.agent_runs where activity_id=$1',[current.activityId])).rows,'Run sequence missing').sequence;
  await db.query(`insert into app.agent_runs(id,activity_id,user_id,account_id,sequence,manager_kind,manager_connection_id,manager_lifecycle_revision,assignment_id,assignment_revision,grant_id,grant_revision,safety_revision,mode,trigger,input_digest,correlation_id,causation_id,state,created_at,started_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'automatic',jsonb_build_object('kind','automatic_task','taskId',$14::text),$15,$16,$2,'running',$17::timestamptz,$17::timestamptz)`,[runId,current.activityId,current.userId,current.mailboxId,seq,current.manager.kind,current.manager.kind==='agent_connection'?current.manager.connectionId:null,current.managerLifecycleRevision,current.assignmentId,current.assignmentRevision,current.grantId,current.grantRevision,current.safetyRevision,current.id,digest(current.id),`task:${current.id}`,now]);}
  await db.query(`insert into app.agent_task_delivery_attempts(id,task_id,number,lease_generation,run_id,manager_kind,manager_connection_id,request_id,request_digest,started_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::timestamptz)`,[randomUUID(),current.id,next.attemptCount,next.leaseGeneration,runId,current.manager.kind,current.manager.kind==='agent_connection'?current.manager.connectionId:null,requestId,digest(requestId),now]);
  await this.persist(db,next,current.version); return {task:next,runId,leaseToken:raw};
 });}
 async heartbeat(taskId:string,generation:number,leaseToken:string,requestId:string,requestDigest:string,now:string,leaseMs=60_000,connectionId?:string):Promise<AgentTask>{return this.mutateReport(taskId,'heartbeat',requestId,requestDigest,async(db,current)=>{
   this.requireConnection(current,connectionId); await this.requireAuthority(db,current); const expires=new Date(Math.min(new Date(now).valueOf()+leaseMs,new Date(current.deadlineAt).valueOf())).toISOString(); return heartbeatAgentTask(current,{taskId,requestId,requestDigest,expectedVersion:current.version,occurredAt:now,leaseGeneration:generation,leaseTokenDigest:digest(leaseToken),leaseExpiresAt:expires});
  },now);}
 async reportResult(taskId:string,generation:number,leaseToken:string,requestId:string,requestDigest:string,result:AgentTaskResult,now:string,connectionId?:string):Promise<AgentTask>{return this.mutateReport(taskId,'result',requestId,requestDigest,async(db,current)=>{
   this.requireConnection(current,connectionId); await this.requireAuthority(db,current);let owned:string[]=[];if(result.kind==='action_requests_emitted')owned=(await db.query<{id:string}>('select id from app.agent_authorized_actions where run_id=$1 and account_id=$2',[current.currentRunId,current.mailboxId])).rows.map(r=>r.id);
   return reportAgentTaskResult(current,{taskId,requestId,requestDigest,expectedVersion:current.version,occurredAt:now,leaseGeneration:generation,leaseTokenDigest:digest(leaseToken),result},owned);
  },now);}
 async reportFailure(taskId:string,generation:number,leaseToken:string,requestId:string,requestDigest:string,errorCode:AgentTaskErrorCode,now:string,connectionId?:string):Promise<AgentTask>{return this.mutateReport(taskId,'failure',requestId,requestDigest,async(db,current)=>{this.requireConnection(current,connectionId);await this.requireAuthority(db,current);return reportAgentTaskFailure(current,{taskId,requestId,requestDigest,expectedVersion:current.version,occurredAt:now,leaseGeneration:generation,leaseTokenDigest:digest(leaseToken),errorCode},new Date(new Date(now).valueOf()+agentTaskBackoffMs(current.attemptCount)).toISOString());},now);}
 async answer(taskId:string,questionId:string,answerDigest:string,continuationRunId:string,requestId:string,requestDigest:string,now:string,connectionId?:string):Promise<AgentTask>{return this.mutateReport(taskId,'answer',requestId,requestDigest,async(db,current)=>{
   this.requireConnection(current,connectionId);await this.requireAuthority(db,current);
   const next=answerAgentTaskQuestion(current,{taskId,questionId,answerDigest,continuationRunId,requestId,requestDigest,expectedVersion:current.version,occurredAt:now});
   await db.query('select id from app.agent_activities where id=$1 for update',[current.activityId]);
   const previous=one((await db.query<{id:string;sequence:number;correlation_id:string}>(`select id,sequence,correlation_id from app.agent_runs where activity_id=$1 order by sequence desc limit 1`,[current.activityId])).rows,'Prior Run missing');
   await db.query(`insert into app.agent_runs(id,activity_id,user_id,account_id,sequence,manager_kind,manager_connection_id,manager_lifecycle_revision,assignment_id,assignment_revision,grant_id,grant_revision,safety_revision,mode,trigger,input_digest,correlation_id,causation_id,state,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'automatic',jsonb_build_object('kind','question_answer','questionId',$14::text,'taskId',$15::text),$16,$17,$18,'created',$19::timestamptz)`,[continuationRunId,current.activityId,current.userId,current.mailboxId,previous.sequence+1,current.manager.kind,current.manager.kind==='agent_connection'?current.manager.connectionId:null,current.managerLifecycleRevision,current.assignmentId,current.assignmentRevision,current.grantId,current.grantRevision,current.safetyRevision,questionId,current.id,answerDigest,`task-answer:${current.id}:${questionId}`,previous.id,now]);
   const eventSeq=one((await db.query<{sequence:number}>(`select coalesce(max(sequence),0)::integer+1 as sequence from app.agent_activity_events where activity_id=$1`,[current.activityId])).rows,'Event sequence missing').sequence;
   await db.query(`insert into app.agent_activity_events(id,activity_id,user_id,account_id,sequence,correlation_id,causation_id,occurred_at,detail) values($1,$2,$3,$4,$5,$6,$7,$8::timestamptz,jsonb_build_object('type','question_answered','runId',$9::text,'answerDigest',$10::text))`,[randomUUID(),current.activityId,current.userId,current.mailboxId,eventSeq,`task-answer:${current.id}:${questionId}`,previous.id,now,continuationRunId,answerDigest]);
   await this.outbox(db,next,'question_answered',answerDigest,`task:${current.id}`,now);return next;
  },now);}
 async completeActionVerification(taskId:string,now:string):Promise<AgentTask>{return this.sql.transaction(async db=>{
  const current=taskFrom(one((await db.query<TaskRow>('select * from app.agent_tasks where id=$1 for update',[taskId])).rows,'Task not found'));
  if(current.result?.kind!=='action_requests_emitted')throw new Error('Task has no Action requests.');
  const states=await db.query<{state:string}>('select state from app.agent_authorized_actions where id=any($1::uuid[]) and run_id in (select run_id from app.agent_task_delivery_attempts where task_id=$2)',[current.result.actionIds,taskId]);
  if(states.rows.length!==current.result.actionIds.length||states.rows.some(row=>row.state!=='verified'))throw new Error('ACTION_VERIFICATION_INCOMPLETE');
  const next=completeAgentTaskActionVerification(current,now);await this.persist(db,next,current.version);await this.outbox(db,next,'task_terminal',digest(taskId),`task:${taskId}`,now);return next;
 });}
 async cancel(taskId:string,now:string,connectionId?:string):Promise<AgentTask>{return this.sql.transaction(async db=>{const current=taskFrom(one((await db.query<TaskRow>('select * from app.agent_tasks where id=$1 for update',[taskId])).rows,'Task not found'));this.requireConnection(current,connectionId);if(connectionId)await this.requireAuthority(db,current);const next=cancelAgentTask(current,now);await this.persist(db,next,current.version);if(current.currentRunId)await db.query(`update app.agent_runs set state='completed',outcome='cancelled',error_code='OWNER_CANCELLED',completed_at=$2::timestamptz where id=$1 and state='running'`,[current.currentRunId,now]);await this.outbox(db,next,'task_terminal',digest(taskId),`task:${taskId}`,now);return next;});}
 async recordReceipt(taskId:string,outboxId:string|null,transport:string,receiptId:string,at:string):Promise<void>{await this.sql.query(`insert into app.agent_task_receipts(id,task_id,outbox_id,transport,receipt_id,received_at) values($1,$2,$3,$4,$5,$6::timestamptz) on conflict(transport,receipt_id) do nothing`,[randomUUID(),taskId,outboxId,transport,receiptId,at]);}
 async reconcileVerifiedActions(now:string,limit=100):Promise<number>{const ids=(await this.sql.query<{id:string}>(`select id from app.agent_tasks where state='awaiting_action_verification' order by updated_at limit $1`,[limit])).rows;let completed=0;for(const row of ids){try{await this.completeActionVerification(row.id,now);completed++;}catch(error){if(!(error instanceof Error)||error.message!=='ACTION_VERIFICATION_INCOMPLETE')throw error;}}return completed;}
 async materializeBlocked(now:string,limit=100):Promise<number>{return this.sql.transaction(async db=>{
  await db.query(`insert into app.agent_task_blocks(activity_id,user_id,account_id,reason,available_at) select j.activity_id,a.user_id,a.account_id,'LEGACY_PENDING_JOB',least(j.available_at,$1::timestamptz) from app.agent_jobs j join app.agent_activities a on a.id=j.activity_id left join app.agent_tasks t on t.activity_id=j.activity_id where j.state='pending' and t.id is null on conflict(activity_id) do nothing`,[now]);
  const rows=await db.query<TaskRow>(`select b.*,ma.id assignment_id,ma.revision assignment_revision,ma.manager_kind,ma.agent_connection_id manager_connection_id,c.lifecycle_revision manager_lifecycle_revision,g.id grant_id,g.revision grant_revision,s.revision safety_revision from app.agent_task_blocks b join app.mailbox_manager_assignments ma on ma.user_id=b.user_id and ma.account_id=b.account_id join app.agent_capability_grants g on g.user_id=b.user_id and g.account_id=b.account_id and g.manager_kind=ma.manager_kind and g.agent_connection_id is not distinct from ma.agent_connection_id cross join app.agent_safety_ceiling s left join app.agent_connections c on c.id=ma.agent_connection_id where b.available_at<=$1::timestamptz and ma.manager_kind<>'none' and ma.automatic_processing_enabled and g.state='active' and 'automatic'=any(g.invocation_modes) and 'mail.read'=any(g.capabilities) and 'automatic'=any(s.invocation_modes) and 'mail.read'=any(s.capabilities) and (ma.manager_kind='mastra' or (c.state='connected')) order by b.created_at for update of b skip locked limit $2`,[now,limit]);
  for(const row of rows.rows){const id=randomUUID(),external=row['manager_kind']==='agent_connection';const inserted=await db.query<TaskRow>(`insert into app.agent_tasks(id,enqueue_key,activity_id,user_id,account_id,manager_kind,manager_connection_id,manager_lifecycle_revision,assignment_id,assignment_revision,grant_id,grant_revision,safety_revision,state,pending_reason,version,attempt_count,max_attempts,lease_generation,available_at,deadline_at,created_at,updated_at) values($1,'arrival:'||$2::uuid::text,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'pending','initial',1,0,5,0,$13::timestamptz,$13::timestamptz+interval '24 hours',$13::timestamptz,$13::timestamptz) on conflict(enqueue_key) do nothing returning *`,[id,row['activity_id'],row['user_id'],row['account_id'],row['manager_kind'],external?row['manager_connection_id']:null,external?row['manager_lifecycle_revision']:null,row['assignment_id'],row['assignment_revision'],row['grant_id'],row['grant_revision'],row['safety_revision'],now]);const taskRow=inserted.rows[0];if(taskRow){const task=taskFrom(taskRow);await this.outbox(db,task,'task_available',digest(task.id),`arrival:${task.activityId}`,now);await db.query('delete from app.agent_task_blocks where activity_id=$1',[task.activityId]);}}
  return rows.rows.length;
 });}
 async reconcileExpired(now:string,limit=100):Promise<number>{return this.sql.transaction(async db=>{const rows=await db.query<TaskRow>(`select * from app.agent_tasks where state='leased' and lease_expires_at<$1::timestamptz order by lease_expires_at for update skip locked limit $2`,[now,limit]);for(const row of rows.rows){const t=taskFrom(row),next=expireAgentTaskLease(t,now,new Date(new Date(now).valueOf()+agentTaskBackoffMs(t.attemptCount)).toISOString());await this.persist(db,next,t.version);await db.query(`update app.agent_task_delivery_attempts set ended_at=$2::timestamptz,error_code='LEASE_EXPIRED' where task_id=$1 and lease_generation=$3 and ended_at is null`,[t.id,now,t.leaseGeneration]);
   if(t.currentRunId)await db.query(`update app.agent_runs set state='completed',outcome='failed',error_code='LEASE_EXPIRED',completed_at=$2::timestamptz where id=$1 and state='running'`,[t.currentRunId,now]);
   if(next.state==='pending')await this.outbox(db,next,'task_available',digest(next.id),`task:${next.id}`,now);}return rows.rows.length;});}
 async claimOutbox(limit=100,staleAfterSeconds=300):Promise<Readonly<{claimToken:string;rows:readonly TaskRow[]}>>{return this.sql.transaction(async db=>{const token=randomUUID();const claimed=await db.query<TaskRow>(`with candidates as (select id from app.agent_task_outbox where published_at is null and dead_lettered_at is null and available_at<=now() and (claimed_at is null or claimed_at<now()-make_interval(secs=>$2)) order by occurred_at for update skip locked limit $1) update app.agent_task_outbox o set claim_token=$3,claimed_at=now(),publish_attempts=publish_attempts+1 from candidates c where o.id=c.id returning o.*`,[limit,staleAfterSeconds,token]);return {claimToken:token,rows:claimed.rows};});}
 async pendingOutbox(limit=100):Promise<readonly TaskRow[]>{return (await this.claimOutbox(limit)).rows;}
 async markOutboxPublished(id:string,at:string,claimToken?:string):Promise<void>{await this.sql.query('update app.agent_task_outbox set published_at=$2::timestamptz,claim_token=null,claimed_at=null,last_error=null where id=$1 and published_at is null and ($3::uuid is null or claim_token=$3::uuid)',[id,at,claimToken??null]);}
 async markOutboxFailed(id:string,claimToken:string,error:string,now:string,maxAttempts=10):Promise<void>{await this.sql.query(`update app.agent_task_outbox set claim_token=null,claimed_at=null,last_error=left($3,500),available_at=$4::timestamptz+make_interval(secs=>least(300,power(2,least(publish_attempts,8))::integer)),dead_lettered_at=case when publish_attempts>=$5 then $4::timestamptz end where id=$1 and claim_token=$2::uuid and published_at is null`,[id,claimToken,error,now,maxAttempts]);}
 async recoverOutboxClaims(now:string,staleAfterSeconds=300):Promise<number>{const result=await this.sql.query(`update app.agent_task_outbox set claim_token=null,claimed_at=null where published_at is null and claimed_at<$1::timestamptz-make_interval(secs=>$2) returning id`,[now,staleAfterSeconds]);return result.rows.length;}
 async replayOutboxDeadLetter(id:string,now:string):Promise<void>{await this.sql.query(`update app.agent_task_outbox set dead_lettered_at=null,last_error=null,available_at=$2::timestamptz,publish_attempts=0 where id=$1 and published_at is null`,[id,now]);}
 private async mutateReport(taskId:string,kind:string,requestId:string,requestDigest:string,evolve:(db:SqlClient,t:AgentTask)=>Promise<AgentTask>,now:string):Promise<AgentTask>{return this.sql.transaction(async db=>{
  // Serialize every report for a Task before classifying idempotency. This makes the
  // unique request key and the returned snapshot one atomic decision.
  await db.query('select id from app.agent_tasks where id=$1 for update',[taskId]);
  const prior=await db.query<{request_digest:string;response_snapshot:unknown}>(`select request_digest,response_snapshot from app.agent_task_reports where task_id=$1 and request_id=$2`,[taskId,requestId]);
  if(prior.rows[0]){if(prior.rows[0].request_digest!==requestDigest)throw new Error('IDEMPOTENCY_MISMATCH');const snapshot=prior.rows[0].response_snapshot as {task?:unknown};return agentTaskSchema.parse(snapshot.task);}
  const current=taskFrom(one((await db.query<TaskRow>('select * from app.agent_tasks where id=$1',[taskId])).rows,'Task not found'));
  const next=await evolve(db,current);await this.persist(db,next,current.version);
  await db.query(`insert into app.agent_task_reports(id,task_id,attempt_id,lease_generation,kind,request_id,request_digest,accepted,occurred_at,response_snapshot) values($1,$2,(select id from app.agent_task_delivery_attempts where task_id=$2 and lease_generation=$3),$3,$4,$5,$6,true,$7::timestamptz,$8::jsonb)`,[randomUUID(),taskId,current.leaseGeneration,kind,requestId,requestDigest,now,JSON.stringify({task:next})]);
  if(next.state!=='leased'){
   await db.query('update app.agent_task_delivery_attempts set ended_at=$2::timestamptz,error_code=$3 where task_id=$1 and lease_generation=$4 and ended_at is null',[taskId,now,next.lastErrorCode,current.leaseGeneration]);
   const outcome=next.result?.kind==='question'?'question_asked':next.result?.kind==='action_requests_emitted'?'action_requests_emitted':next.state==='completed'?'no_action':next.state==='cancelled'?'cancelled':'failed';
   if(current.currentRunId)await db.query(`update app.agent_runs set state='completed',outcome=$2,error_code=$3,completed_at=$4::timestamptz where id=$1 and state='running'`,[current.currentRunId,outcome,next.lastErrorCode,now]);
  }
  if(['completed','dead_letter','cancelled'].includes(next.state))await this.outbox(db,next,'task_terminal',digest(taskId),`task:${taskId}`,now);return next;
 });}
 private requireConnection(task:AgentTask,connectionId:string|undefined):void{if(connectionId!==undefined&&(task.manager.kind!=='agent_connection'||task.manager.connectionId!==connectionId))throw new Error('AUTHENTICATED_CONNECTION_MISMATCH');}
 private authoritySql(a:string):string{return `exists(select 1 from app.mailbox_manager_assignments ma join app.agent_capability_grants g on g.id=${a}.grant_id join app.agent_safety_ceiling s on s.singleton=true left join app.agent_connections c on c.id=${a}.manager_connection_id where ma.id=${a}.assignment_id and ma.revision=${a}.assignment_revision and ma.manager_kind=${a}.manager_kind and ma.agent_connection_id is not distinct from ${a}.manager_connection_id and ma.automatic_processing_enabled and g.revision=${a}.grant_revision and g.state='active' and 'automatic'=any(g.invocation_modes) and 'mail.read'=any(g.capabilities) and s.revision=${a}.safety_revision and 'automatic'=any(s.invocation_modes) and 'mail.read'=any(s.capabilities) and (${a}.manager_kind='mastra' or (c.state='connected' and c.lifecycle_revision=${a}.manager_lifecycle_revision)))`;}
 private async requireAuthority(db:SqlClient,t:AgentTask):Promise<void>{const ok=await db.query<{ok:boolean}>(`select ${this.authoritySql('t')} as ok from app.agent_tasks t where t.id=$1`,[t.id]);if(ok.rows[0]?.ok!==true)throw new Error('AUTHORIZATION_REVOKED');}
 private async persist(db:SqlClient,t:AgentTask,expected:number):Promise<void>{const l=t.lease;const result=await db.query(`update app.agent_tasks set state=$3,pending_reason=$4,version=$5,attempt_count=$6,lease_generation=$7,lease_token_digest=$8,lease_claimed_by=$9,lease_claimed_at=$10::timestamptz,lease_heartbeat_at=$11::timestamptz,lease_expires_at=$12::timestamptz,current_run_id=$13,result=$14::jsonb,last_error_code=$15,available_at=$16::timestamptz,updated_at=$17::timestamptz,completed_at=$18::timestamptz,obsolete_at=$19::timestamptz where id=$1 and version=$2 returning id`,[t.id,expected,t.state,t.pendingReason,t.version,t.attemptCount,t.leaseGeneration,l?.tokenDigest??null,l?.claimedBy??null,l?.claimedAt??null,l?.heartbeatAt??null,l?.expiresAt??null,t.currentRunId,t.result,t.lastErrorCode,t.availableAt,t.updatedAt,t.completedAt,t.obsoleteAt]);if(result.rows.length!==1)throw new Error('STALE_VERSION');}
 private async outbox(db:SqlClient,t:AgentTask,event:string,payloadDigest:string,correlationId:string,at:string):Promise<void>{await db.query(`insert into app.agent_task_outbox(id,task_id,activity_id,account_id,event,task_version,payload_digest,correlation_id,occurred_at,available_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9::timestamptz,$9::timestamptz) on conflict(task_id,task_version,event) do nothing`,[randomUUID(),t.id,t.activityId,t.mailboxId,event,t.version,payloadDigest,correlationId,at]);}
}

/** Stable mutation key journal: unknown/unverifiable outcomes are authoritative and never auto-retried. */
export class AgentMutationJournal {constructor(private readonly sql:SqlClient){}async begin(accountId:string,operation:string,key:string,requestDigest:string):Promise<'new'|'replay'>{return this.sql.transaction(async db=>{const inserted=await db.query(`insert into app.agent_mutation_idempotency(account_id,operation,idempotency_key,request_digest,state) values($1,$2,$3,$4,'started') on conflict do nothing returning account_id`,[accountId,operation,key,requestDigest]);if(inserted.rows.length)return 'new';const row=one((await db.query<{request_digest:string}>('select request_digest from app.agent_mutation_idempotency where account_id=$1 and operation=$2 and idempotency_key=$3',[accountId,operation,key])).rows,'Journal disappeared');if(row.request_digest!==requestDigest)throw new Error('IDEMPOTENCY_MISMATCH');return 'replay';});}async finish(accountId:string,operation:string,key:string,state:'succeeded'|'failed'|'unverifiable',result:unknown):Promise<void>{await this.sql.query(`update app.agent_mutation_idempotency set state=$4,result=$5::jsonb,updated_at=now() where account_id=$1 and operation=$2 and idempotency_key=$3 and state='started'`,[accountId,operation,key,state,result]);}}
