import type { PostgresOAuthService, TokenResult } from './service.js';
export type OAuthHttpRequest={method:string;query:Readonly<Record<string,string|undefined>>;origin:string|null;body:Readonly<Record<string,unknown>>;userId:string|null};
export type OAuthHttpResponse={status:number;body?:Readonly<Record<string,unknown>>;headers:Readonly<Record<string,string>>};
const headers={'Cache-Control':'no-store','Pragma':'no-cache'} as const;
const error=(status:number,value:string):OAuthHttpResponse=>({status,body:{error:value},headers});
const required=(value:unknown,max=2048):string|null=>typeof value==='string'&&value.length>0&&value.length<=max?value:null;
export function parseFormEncoded(body:Buffer,maxBytes=8192):Readonly<Record<string,string>>{if(body.length>maxBytes)throw new RangeError('Payload too large');const params=new URLSearchParams(body.toString('utf8'));const result:Record<string,string>={};for(const [key,value] of params){if(key.length>128||value.length>4096||key in result)throw new TypeError('Invalid form');result[key]=value;}return result;}
export function createOAuthRoutes(service:PostgresOAuthService,appOrigin:string){return {
 metadata:():OAuthHttpResponse=>({status:200,body:service.metadata(),headers:{...headers,'Content-Type':'application/json; charset=utf-8'}}),
 authorizeGet:async(req:OAuthHttpRequest):Promise<OAuthHttpResponse>=>{if(!req.userId)return {status:302,headers:{...headers,Location:new URL('/login',appOrigin).toString()}};const q=req.query;const input=authorizationInput(req.userId,q);if(!input)return error(400,'invalid_request');const consent=await service.beginConsent(input,required(q['state']));return consent?{status:200,body:{clientName:consent.clientName,clientId:input.clientId,redirectUri:input.redirectUri,scope:input.scope,request_token:consent.requestToken,mailboxes:consent.mailboxes},headers}:error(400,'invalid_request');},
 authorizePost:async(req:OAuthHttpRequest):Promise<OAuthHttpResponse>=>{if(req.origin!==appOrigin)return error(403,'forbidden');if(!req.userId)return error(401,'unauthenticated');const requestToken=required(req.body['request_token']);if(!requestToken)return error(400,'invalid_request');if(req.body['decision']==='deny'){const denied=await service.denyConsent(req.userId,requestToken);if(!denied)return error(400,'invalid_request');const redirect=new URL(denied.redirectUri);redirect.searchParams.set('error','access_denied');if(denied.state)redirect.searchParams.set('state',denied.state);return {status:303,headers:{...headers,Location:redirect.toString()}};}if(req.body['decision']!=='allow')return error(400,'invalid_request');const mailboxId=required(req.body['mailbox_id']);if(!mailboxId)return error(400,'invalid_request');const approved=await service.approveConsent(req.userId,requestToken,mailboxId);if(!approved)return error(400,'invalid_request');const redirect=new URL(approved.redirectUri);const state=approved.state;const code=approved.code;redirect.searchParams.set('code',code);if(state)redirect.searchParams.set('state',state);return {status:303,headers:{...headers,Location:redirect.toString()}};},
 token:async(req:OAuthHttpRequest):Promise<OAuthHttpResponse>=>{if(req.method!=='POST')return {status:405,headers:{...headers,Allow:'POST'}};const grant=required(req.body['grant_type']);const clientId=required(req.body['client_id']);if(!grant||!clientId)return error(400,'invalid_request');let result:TokenResult;if(grant==='authorization_code'){const code=required(req.body['code']),redirectUri=required(req.body['redirect_uri']),verifier=required(req.body['code_verifier']);if(!code||!redirectUri||!verifier)return error(400,'invalid_request');result=await service.exchangeCode({code,clientId,redirectUri,verifier});}else if(grant==='refresh_token'){const refreshToken=required(req.body['refresh_token']);if(!refreshToken)return error(400,'invalid_request');result=await service.refresh({refreshToken,clientId});}else return error(400,'unsupported_grant_type');return result.ok?{status:200,body:{access_token:result.accessToken,token_type:'Bearer',expires_in:result.expiresIn,refresh_token:result.refreshToken,scope:'agent:mailbox'},headers}:error(400,result.error);},
 revoke:async(req:OAuthHttpRequest):Promise<OAuthHttpResponse>=>{if(req.method!=='POST')return {status:405,headers:{...headers,Allow:'POST'}};const token=required(req.body['token']),clientId=required(req.body['client_id']);if(!token||!clientId)return error(400,'invalid_request');await service.revoke(token,clientId);return {status:200,body:{},headers};},
};}
function authorizationInput(userId:string,source:Readonly<Record<string,unknown>>){const clientId=required(source['client_id']),redirectUri=required(source['redirect_uri']),scope=required(source['scope']),codeChallenge=required(source['code_challenge']),codeChallengeMethod=required(source['code_challenge_method']);if(!clientId||!redirectUri||!scope||!codeChallenge||!codeChallengeMethod||source['response_type']!=='code')return null;return {userId,clientId,redirectUri,scope,codeChallenge,codeChallengeMethod};}
