import { createHash, createHmac, randomBytes, timingSafeEqual } from 'node:crypto';
import type { Sql, TransactionSql } from 'postgres';
type QuerySql = Sql | TransactionSql;

export const OAUTH_SCOPE = 'agent:mailbox';
export const oauthAudience = (origin: string): string => new URL('/mcp', origin).toString();
export const pkceS256 = (verifier: string): string => createHash('sha256').update(verifier, 'ascii').digest('base64url');
const verifierPattern = /^[A-Za-z0-9._~-]{43,128}$/;
const challengePattern = /^[A-Za-z0-9_-]{43}$/;
export type OAuthError = 'invalid_request' | 'invalid_client' | 'invalid_grant' | 'unsupported_grant_type';
export type TokenResult = { ok: true; accessToken: string; refreshToken: string; expiresIn: number } | { ok: false; error: OAuthError };
export type AccessPrincipal = Readonly<{ credentialId: string; familyId: string; clientId: string; userId: string; connectionId: string; mailboxId: string; audience: string; scopes: readonly string[]; lifecycleRevision: number; assignmentRevision: number; grantRevision: number; safetyRevision: number }>;
type Current = { user_id: string; connection_id: string; account_id: string; lifecycle_revision: number; assignment_revision: number; grant_revision: number; safety_revision: number };
type TokenRow = Current & { token_digest: string; family_id: string; client_id: string; kind: string; generation:number; audience: string; scope: string; expires_at: Date; consumed_at: Date | null; revoked_at: Date | null; family_revoked_at: Date | null };
const rawToken = () => randomBytes(32).toString('base64url');

export class PostgresOAuthService {
  public constructor(private readonly sql: Sql, private readonly origin: string, private readonly hashKey: string, private readonly now: () => Date = () => new Date()) {
    if (Buffer.byteLength(hashKey) < 32) throw new Error('OAUTH_TOKEN_HASH_KEY must be at least 32 bytes');
  }
  public metadata(): Readonly<Record<string, unknown>> { return { issuer: this.origin, authorization_endpoint: new URL('/oauth/authorize', this.origin).toString(), token_endpoint: new URL('/oauth/token', this.origin).toString(), revocation_endpoint: new URL('/oauth/revoke', this.origin).toString(), response_types_supported: ['code'], grant_types_supported: ['authorization_code', 'refresh_token'], code_challenge_methods_supported: ['S256'], token_endpoint_auth_methods_supported: ['none'], scopes_supported: [OAUTH_SCOPE] }; }
  public async beginConsent(input: { userId:string; clientId:string; redirectUri:string; scope:string; codeChallenge:string; codeChallengeMethod:string }, state:string|null): Promise<{requestToken:string;clientName:string;mailboxes:readonly {id:string;email:string}[]}|null> {
    if(input.scope!==OAUTH_SCOPE||input.codeChallengeMethod!=='S256'||!challengePattern.test(input.codeChallenge))return null;
    const rows=await this.sql<{display_name:string;connection_id:string;account_id:string;email:string}[]>`select c.display_name,c.agent_connection_id connection_id,u.account_id,a.email from app.oauth_public_clients c join app.agent_connections x on x.id=c.agent_connection_id and x.user_id=c.user_id and x.state='connected' join app.user_accounts u on u.user_id=c.user_id join app.accounts a on a.id=u.account_id join app.mailbox_manager_assignments m on m.user_id=u.user_id and m.account_id=u.account_id and m.manager_kind='agent_connection' and m.agent_connection_id=x.id join app.agent_capability_grants g on g.user_id=u.user_id and g.account_id=u.account_id and g.agent_connection_id=x.id and g.state='active' where c.client_id=${input.clientId} and c.user_id=${input.userId} and c.revoked_at is null and c.allowed_scope=${input.scope} and ${input.redirectUri}=any(c.redirect_uris)`;
    const first=rows[0];if(!first)return null;const requestToken=rawToken();
    await this.sql`insert into app.oauth_consent_requests(request_digest,client_id,redirect_uri,user_id,connection_id,scope,code_challenge,state,expires_at) values(${this.digest(requestToken)},${input.clientId},${input.redirectUri},${input.userId},${first.connection_id},${input.scope},${input.codeChallenge},${state},${new Date(this.now().getTime()+600000)})`;
    await this.audit('oauth.consent_started',input.userId,{clientId:input.clientId});return {requestToken,clientName:first.display_name,mailboxes:rows.map(r=>({id:r.account_id,email:r.email}))};
  }
  public async consumeConsent(userId:string,requestToken:string,mailboxId:string):Promise<({userId:string;clientId:string;redirectUri:string;connectionId:string;mailboxId:string;scope:string;codeChallenge:string;codeChallengeMethod:'S256';state:string|null})|null>{
    return this.sql.begin(async tx=>{const rows=await tx<{client_id:string;redirect_uri:string;connection_id:string;scope:string;code_challenge:string;state:string|null}[]>`select client_id,redirect_uri,connection_id,scope,code_challenge,state from app.oauth_consent_requests where request_digest=${this.digest(requestToken)} and user_id=${userId} and consumed_at is null and expires_at>${this.now()} for update`;const r=rows[0];if(!r||!await this.current(tx,userId,r.connection_id,mailboxId))return null;await tx`update app.oauth_consent_requests set consumed_at=${this.now()},account_id=${mailboxId} where request_digest=${this.digest(requestToken)}`;return {userId,clientId:r.client_id,redirectUri:r.redirect_uri,connectionId:r.connection_id,mailboxId,scope:r.scope,codeChallenge:r.code_challenge,codeChallengeMethod:'S256',state:r.state};});
  }
  public async grant(input: { userId: string; clientId: string; redirectUri: string; connectionId: string; mailboxId: string; scope: string; codeChallenge: string; codeChallengeMethod: string }): Promise<string | null> {
    const current=await this.current(this.sql,input.userId,input.connectionId,input.mailboxId); if(!current)return null;
    const code = rawToken(); const expires = new Date(this.now().getTime() + 5 * 60_000);
    await this.sql`insert into app.oauth_authorization_codes (code_digest,client_id,redirect_uri,user_id,connection_id,account_id,code_challenge,scope,lifecycle_revision,assignment_revision,grant_revision,safety_revision,expires_at) values (${this.digest(code)},${input.clientId},${input.redirectUri},${input.userId},${input.connectionId},${input.mailboxId},${input.codeChallenge},${input.scope},${current.lifecycle_revision},${current.assignment_revision},${current.grant_revision},${current.safety_revision},${expires})`;
    await this.audit('oauth.consent_allowed',input.userId,{clientId:input.clientId}); return code;
  }
  public async denyConsent(userId:string,requestToken:string):Promise<{redirectUri:string;state:string|null}|null>{return this.sql.begin(async tx=>{const rows=await tx<{redirect_uri:string;state:string|null;client_id:string}[]>`select q.redirect_uri,q.state,q.client_id from app.oauth_consent_requests q join app.oauth_public_clients c on c.client_id=q.client_id and c.user_id=q.user_id and c.agent_connection_id=q.connection_id and c.revoked_at is null and q.redirect_uri=any(c.redirect_uris) and q.scope=c.allowed_scope where q.request_digest=${this.digest(requestToken)} and q.user_id=${userId} and q.consumed_at is null and q.expires_at>${this.now()} for update of q,c`;const r=rows[0];if(!r)return null;await tx`update app.oauth_consent_requests set consumed_at=${this.now()} where request_digest=${this.digest(requestToken)}`;await tx`insert into app.audits(actor_type,actor_id,event,correlation_id,metadata) values('user',${userId},'oauth.consent_denied','oauth',${JSON.stringify({clientId:'bounded'})}::jsonb)`;return {redirectUri:r.redirect_uri,state:r.state};});}
  public async approveConsent(userId:string,requestToken:string,mailboxId:string):Promise<{code:string;redirectUri:string;state:string|null}|null>{return this.sql.begin(async tx=>{const rows=await tx<{client_id:string;redirect_uri:string;connection_id:string;scope:string;code_challenge:string;state:string|null}[]>`select q.client_id,q.redirect_uri,q.connection_id,q.scope,q.code_challenge,q.state from app.oauth_consent_requests q join app.oauth_public_clients c on c.client_id=q.client_id and c.user_id=q.user_id and c.agent_connection_id=q.connection_id and c.revoked_at is null and q.redirect_uri=any(c.redirect_uris) and q.scope=c.allowed_scope where q.request_digest=${this.digest(requestToken)} and q.user_id=${userId} and q.consumed_at is null and q.expires_at>${this.now()} for update of q,c`;const r=rows[0];const current=r?await this.current(tx,userId,r.connection_id,mailboxId):null;if(!r||!current){await tx`insert into app.audits(actor_type,actor_id,event,correlation_id,metadata) values('user',${userId},'oauth.consent_denied','oauth','{}'::jsonb)`;return null;}const code=rawToken(),now=this.now();await tx`update app.oauth_consent_requests set consumed_at=${now},account_id=${mailboxId} where request_digest=${this.digest(requestToken)}`;await tx`insert into app.oauth_authorization_codes(code_digest,client_id,redirect_uri,user_id,connection_id,account_id,code_challenge,scope,lifecycle_revision,assignment_revision,grant_revision,safety_revision,expires_at) values(${this.digest(code)},${r.client_id},${r.redirect_uri},${userId},${r.connection_id},${mailboxId},${r.code_challenge},${r.scope},${current.lifecycle_revision},${current.assignment_revision},${current.grant_revision},${current.safety_revision},${new Date(now.getTime()+300000)})`;await tx`insert into app.audits(actor_type,actor_id,event,correlation_id,metadata) values('user',${userId},'oauth.consent_allowed','oauth',${JSON.stringify({clientId:r.client_id})}::jsonb)`;return {code,redirectUri:r.redirect_uri,state:r.state};});}
  public async exchangeCode(input: { code: string; clientId: string; redirectUri: string; verifier: string }): Promise<TokenResult> {
    if (!verifierPattern.test(input.verifier)) return { ok: false, error: 'invalid_grant' };
    return this.sql.begin(async tx => {
      const rows = await tx<(Current & { code_challenge: string; expires_at: Date; consumed_at: Date | null })[]>`select c.user_id,c.connection_id,c.account_id,c.code_challenge,c.expires_at,c.consumed_at,c.lifecycle_revision,c.assignment_revision,c.grant_revision,c.safety_revision from app.oauth_authorization_codes c join app.oauth_public_clients pc on pc.client_id=c.client_id and pc.revoked_at is null join app.agent_connections x on x.id=c.connection_id and x.user_id=c.user_id and x.state='connected' join app.user_accounts u on u.user_id=c.user_id and u.account_id=c.account_id join app.mailbox_manager_assignments a on a.user_id=c.user_id and a.account_id=c.account_id and a.manager_kind='agent_connection' and a.agent_connection_id=c.connection_id join app.agent_capability_grants g on g.user_id=c.user_id and g.account_id=c.account_id and g.agent_connection_id=c.connection_id and g.state='active' cross join app.agent_safety_ceiling s where c.lifecycle_revision=x.lifecycle_revision and c.assignment_revision=a.revision and c.grant_revision=g.revision and c.safety_revision=s.revision and c.code_digest=${this.digest(input.code)} and c.client_id=${input.clientId} and c.redirect_uri=${input.redirectUri} for update of c`;
      const row=rows[0]; const now=this.now();
      if (!row || row.consumed_at || row.expires_at <= now || !safeEqual(row.code_challenge, pkceS256(input.verifier))) {await tx`insert into app.audits(actor_type,event,correlation_id,metadata) values('system','oauth.code_denied','oauth',${JSON.stringify({clientId:input.clientId})}::jsonb)`;return {ok:false,error:'invalid_grant'} as const;}
      await tx`update app.oauth_authorization_codes set consumed_at=${now} where code_digest=${this.digest(input.code)}`;
      const families=await tx<{id:string}[]>`insert into app.oauth_token_families (client_id,user_id,connection_id,account_id) values (${input.clientId},${row.user_id},${row.connection_id},${row.account_id}) returning id`;
      const family=families[0]; if(!family)throw new Error('Token family creation failed'); await tx`insert into app.audits(actor_type,actor_id,event,correlation_id,metadata) values('user',${row.user_id},'oauth.code_exchanged','oauth',${JSON.stringify({clientId:input.clientId})}::jsonb)`; return this.issue(tx, family.id, input.clientId, row);
    });
  }
  public async refresh(input: { refreshToken: string; clientId: string }): Promise<TokenResult> {
    return this.sql.begin(async tx => {
      const rows=await tx<TokenRow[]>`select t.*,f.client_id,f.user_id,f.connection_id,f.account_id,f.revoked_at family_revoked_at,f.current_generation from app.oauth_tokens t join app.oauth_token_families f on f.id=t.family_id join app.oauth_public_clients pc on pc.client_id=f.client_id and pc.revoked_at is null where t.token_digest=${this.digest(input.refreshToken)} and t.kind='refresh' for update of t,f`;
      const old=rows[0]; const now=this.now(); if (!old || old.client_id!==input.clientId || old.revoked_at || old.family_revoked_at || old.expires_at<=now) {await tx`insert into app.audits(actor_type,event,correlation_id,metadata) values('system','oauth.refresh_denied','oauth',${JSON.stringify({clientId:input.clientId})}::jsonb)`;return {ok:false,error:'invalid_grant'} as const;}
      if (old.consumed_at || old.generation < (old as TokenRow & {current_generation:number}).current_generation) { await tx`update app.oauth_token_families set revoked_at=coalesce(revoked_at,${now}) where id=${old.family_id}`; await tx`update app.oauth_tokens set revoked_at=coalesce(revoked_at,${now}) where family_id=${old.family_id}`; await tx`insert into app.audits(actor_type,actor_id,event,correlation_id,metadata) values('system',null,'oauth.refresh_reuse','oauth','{}'::jsonb)`; return {ok:false,error:'invalid_grant'} as const; }
      const current=await this.current(tx,old.user_id,old.connection_id,old.account_id); if(!current){ await tx`insert into app.audits(actor_type,event,correlation_id,metadata) values('system','oauth.refresh_invalidated','oauth','{}'::jsonb)`; await tx`update app.oauth_token_families set revoked_at=${now} where id=${old.family_id} and revoked_at is null`; return {ok:false,error:'invalid_grant'} as const; }
      await tx`update app.oauth_tokens set consumed_at=${now} where token_digest=${old.token_digest}`;
      const issued=await this.issue(tx,old.family_id,input.clientId,current);await tx`insert into app.audits(actor_type,actor_id,event,correlation_id,metadata) values('user',${old.user_id},'oauth.refresh_rotated','oauth',${JSON.stringify({clientId:input.clientId})}::jsonb)`;return issued;
    });
  }
  public async revoke(token: string, clientId: string): Promise<void> { const digest=this.digest(token); await this.sql.begin(async tx=>{ const rows=await tx<{family_id:string;kind:string}[]>`select t.family_id,t.kind from app.oauth_tokens t join app.oauth_token_families f on f.id=t.family_id where t.token_digest=${digest} and f.client_id=${clientId} for update of t,f`; const row=rows[0]; if(!row){await tx`insert into app.audits(actor_type,event,correlation_id,metadata) values('system','oauth.revoke_unknown','oauth',${JSON.stringify({clientId})}::jsonb)`;return;} if(row.kind==='refresh'){ await tx`update app.oauth_token_families set revoked_at=coalesce(revoked_at,${this.now()}) where id=${row.family_id}`; await tx`update app.oauth_tokens set revoked_at=coalesce(revoked_at,${this.now()}) where family_id=${row.family_id}`; } else await tx`update app.oauth_tokens set revoked_at=coalesce(revoked_at,${this.now()}) where token_digest=${digest}`; await tx`insert into app.audits(actor_type,event,correlation_id,metadata) values('system','oauth.token_revoked','oauth',${JSON.stringify({clientId})}::jsonb)`; }); }
  /** Fresh principal seam: every invocation reloads ownership, lifecycle, assignment, grant and safety revisions. */
  public async verifyAccess(token:string):Promise<AccessPrincipal|null>{return this.sql.begin(async tx=>{const rows=await tx<(TokenRow&Current)[]>`select t.*,f.client_id,f.user_id,f.connection_id,f.account_id,f.revoked_at family_revoked_at,f.current_generation,x.lifecycle_revision live_lifecycle_revision,a.revision live_assignment_revision,g.revision live_grant_revision,s.revision live_safety_revision from app.oauth_tokens t join app.oauth_token_families f on f.id=t.family_id join app.oauth_public_clients pc on pc.client_id=f.client_id and pc.revoked_at is null join app.agent_connections x on x.id=f.connection_id and x.user_id=f.user_id and x.state='connected' join app.user_accounts u on u.user_id=f.user_id and u.account_id=f.account_id join app.mailbox_manager_assignments a on a.user_id=f.user_id and a.account_id=f.account_id and a.manager_kind='agent_connection' and a.agent_connection_id=f.connection_id join app.agent_capability_grants g on g.user_id=f.user_id and g.account_id=f.account_id and g.agent_connection_id=f.connection_id and g.state='active' cross join app.agent_safety_ceiling s where t.token_digest=${this.digest(token)} and t.kind='access'`;const row=rows[0];if(!row||row.revoked_at||row.family_revoked_at||row.expires_at<=this.now()||row.audience!==oauthAudience(this.origin)||row.lifecycle_revision!==(row as unknown as {live_lifecycle_revision:number}).live_lifecycle_revision||row.assignment_revision!==(row as unknown as {live_assignment_revision:number}).live_assignment_revision||row.grant_revision!==(row as unknown as {live_grant_revision:number}).live_grant_revision||row.safety_revision!==(row as unknown as {live_safety_revision:number}).live_safety_revision){await tx`insert into app.audits(actor_type,event,correlation_id,metadata) values('system','oauth.access_denied','oauth','{}'::jsonb)`;return null;}return {credentialId:row.token_digest,familyId:row.family_id,clientId:row.client_id,userId:row.user_id,connectionId:row.connection_id,mailboxId:row.account_id,audience:row.audience,scopes:[row.scope],lifecycleRevision:row.lifecycle_revision,assignmentRevision:row.assignment_revision,grantRevision:row.grant_revision,safetyRevision:row.safety_revision};});}
  private async current(sql: QuerySql,userId:string,connectionId:string,accountId:string):Promise<Current|null>{ const rows=await sql<Current[]>`select x.user_id,x.id connection_id,u.account_id,x.lifecycle_revision,a.revision assignment_revision,g.revision grant_revision,s.revision safety_revision from app.agent_connections x join app.user_accounts u on u.user_id=x.user_id and u.account_id=${accountId} join app.mailbox_manager_assignments a on a.user_id=u.user_id and a.account_id=u.account_id and a.manager_kind='agent_connection' and a.agent_connection_id=x.id join app.agent_capability_grants g on g.user_id=u.user_id and g.account_id=u.account_id and g.agent_connection_id=x.id and g.state='active' cross join app.agent_safety_ceiling s where x.user_id=${userId} and x.id=${connectionId} and x.state='connected'`; return rows[0]??null; }
  private async issue(sql:QuerySql,familyId:string,clientId:string,current:Current):Promise<TokenResult>{ const generations=await sql<{current_generation:number}[]>`update app.oauth_token_families set current_generation=current_generation+1 where id=${familyId} and client_id=${clientId} and revoked_at is null and expires_at>${this.now()} returning current_generation`;const generation=generations[0]?.current_generation;if(generation===undefined)return {ok:false,error:'invalid_grant'}; const accessToken=rawToken(),refreshToken=rawToken(),now=this.now(),audience=oauthAudience(this.origin); const values={...current}; await sql`insert into app.oauth_tokens (token_digest,family_id,kind,generation,audience,scope,lifecycle_revision,assignment_revision,grant_revision,safety_revision,expires_at) values (${this.digest(accessToken)},${familyId},'access',${generation},${audience},${OAUTH_SCOPE},${values.lifecycle_revision},${values.assignment_revision},${values.grant_revision},${values.safety_revision},${new Date(now.getTime()+15*60_000)}),(${this.digest(refreshToken)},${familyId},'refresh',${generation},${audience},${OAUTH_SCOPE},${values.lifecycle_revision},${values.assignment_revision},${values.grant_revision},${values.safety_revision},${new Date(now.getTime()+30*24*60*60_000)})`; return {ok:true,accessToken,refreshToken,expiresIn:900}; }
  private async audit(event:string,actorId:string|null,metadata:Readonly<Record<string,string>>={}):Promise<void>{await this.sql`insert into app.audits(actor_type,actor_id,event,correlation_id,metadata) values(${actorId?'user':'system'},${actorId},${event},'oauth',${JSON.stringify(metadata)}::jsonb)`;}
  private digest(value:string):string{return createHmac('sha256',this.hashKey).update(value).digest('base64url');}
}
function safeEqual(a:string,b:string):boolean{const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y);}
