import * as React from 'react';
import { Alert,AlertDescription } from '@/components/heroui/alert.js';
import { Badge } from '@/components/heroui/badge.js';
import { Button } from '@/components/heroui/button.js';
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from '@/components/heroui/card.js';
import { NativeSelect,NativeSelectOption } from '@/components/heroui/native-select.js';
import type { ManagerChoice,ManagerSettingsView,MailboxManagerView } from '../agent-connections/contracts.js';
const key=(m:ManagerChoice)=>m.kind==='agent_connection'?`connection:${m.connectionId}`:m.kind;
const parse=(v:string):ManagerChoice=>v.startsWith('connection:')?{kind:'agent_connection',connectionId:v.slice(11)}:v==='none'?{kind:'none'}:{kind:'mastra'};
export type ManagerMutations={setDefault:(manager:ManagerChoice,revision:number)=>Promise<void>;setLifecycle:(id:string,state:'connected'|'paused'|'disconnected'|'security_revoked',revision:number)=>Promise<void>;setAssignment:(mailbox:MailboxManagerView,manager:ManagerChoice,automatic:boolean)=>Promise<void>;reapprove:(mailbox:MailboxManagerView)=>Promise<void>};
export function MailboxManagerSettings({settings,mutations,online=true}:{settings:ManagerSettingsView;mutations:ManagerMutations;online?:boolean}){const defaultManager=settings.defaultManager;const [busy,setBusy]=React.useState('');const [notice,setNotice]=React.useState('');const act=(id:string,work:()=>Promise<void>)=>{if(!online){setNotice('You are offline. No setting was changed; reconnect and try again.');return;}setBusy(id);setNotice('');void work().then(()=>{ setNotice('Manager settings updated.'); }).catch(()=>{ setNotice('Settings changed or could not be saved. Reload and try again.'); }).finally(()=>{ setBusy(''); });};const choices=(none=true)=><>{none?<NativeSelectOption value="none">None</NativeSelectOption>:null}<NativeSelectOption value="mastra">Mastra</NativeSelectOption>{settings.connections.map(c=><NativeSelectOption key={c.id} value={`connection:${c.id}`}>{c.displayName}</NativeSelectOption>)}</>;
 return <section aria-labelledby="manager-settings-title" className="grid gap-4"><header><h2 id="manager-settings-title" className="text-lg font-semibold">Mailbox Managers</h2><p className="text-sm text-muted-foreground">Assignment chooses who may manage a Mailbox. Grant approval separately authorizes capabilities. Unavailable work remains pending and has no fallback.</p></header><p role="status" aria-live="polite" className="text-sm">{notice}</p>{defaultManager?<Card><CardHeader><CardTitle>Default for future Mailboxes</CardTitle><CardDescription>Changing this affects only Mailboxes added later. Existing assignments are not changed.</CardDescription></CardHeader><CardContent><NativeSelect aria-label="Default Mailbox Manager" value={key(defaultManager.manager)} disabled={!!busy||!online} onChange={e=>{ act('default',()=>mutations.setDefault(parse(e.target.value),defaultManager.revision)); }}>{choices(false)}</NativeSelect></CardContent></Card>:null}<div className="grid gap-3">{settings.mailboxes.map(mailbox=><MailboxCard key={mailbox.mailboxId} mailbox={mailbox} settings={settings} busy={!!busy} online={online} act={act} mutations={mutations}/>)}</div><section aria-labelledby="connections-title"><h3 id="connections-title" className="font-semibold">Agent Connections</h3><div className="mt-2 grid gap-2">{settings.connections.map(c=><Card key={c.id}><CardContent className="flex min-w-0 flex-wrap items-center justify-between gap-2"><div><strong>{c.displayName}</strong> <Badge variant="outline">{c.state}</Badge><p className="text-sm text-muted-foreground">Lifecycle revision {c.lifecycleRevision}</p></div><div className="flex flex-wrap gap-2">{c.state==='connected'?<Button variant="outline" disabled={!!busy||!online} onClick={()=>{ act(c.id,()=>mutations.setLifecycle(c.id,'paused',c.lifecycleRevision)); }}>Pause</Button>:c.state==='paused'||c.state==='disconnected'?<Button variant="outline" disabled={!!busy||!online} onClick={()=>{ act(c.id,()=>mutations.setLifecycle(c.id,'connected',c.lifecycleRevision)); }}>Resume</Button>:null}{c.state!=='security_revoked'?<Button variant="destructive" disabled={!!busy||!online} onClick={()=>{if(confirm('Security revoke this connection? Every Mailbox grant will require explicit reapproval.'))act(c.id,()=>mutations.setLifecycle(c.id,'security_revoked',c.lifecycleRevision));}}>Security revoke</Button>:<Alert><AlertDescription>Security revoked. A verified reconnect is required, then every Mailbox grant must be reapproved.</AlertDescription></Alert>}</div></CardContent></Card>)}</div></section></section>;
}
function MailboxCard({mailbox,settings,busy,online,act,mutations}:{mailbox:MailboxManagerView;settings:ManagerSettingsView;busy:boolean;online:boolean;act:(id:string,w:()=>Promise<void>)=>void;mutations:ManagerMutations}){const [choice,setChoice]=React.useState(key(mailbox.assignment.manager));const automatic=mailbox.assignment.automaticProcessingEnabled;const changed=choice!==key(mailbox.assignment.manager);return <Card><CardHeader><CardTitle>{mailbox.mailboxLabel}</CardTitle><CardDescription>Manager assignment revision {mailbox.assignment.revision}</CardDescription></CardHeader><CardContent className="grid gap-3"><label className="grid gap-1 text-sm font-medium">Assigned Manager<NativeSelect value={choice} disabled={busy||!online} onChange={e=>{ setChoice(e.target.value); }}><NativeSelectOption value="none">None</NativeSelectOption><NativeSelectOption value="mastra">Mastra</NativeSelectOption>{settings.connections.map(c=><NativeSelectOption key={c.id} value={`connection:${c.id}`}>{c.displayName}</NativeSelectOption>)}</NativeSelect></label>{changed?<Button disabled={busy||!online} onClick={()=>{ act(mailbox.mailboxId,()=>mutations.setAssignment(mailbox,parse(choice),false)); }}>Confirm assignment change</Button>:<label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={automatic} disabled={busy||!online||mailbox.grant?.state!=='active'||mailbox.assignment.manager.kind==='none'} onChange={e=>{ act(mailbox.mailboxId,()=>mutations.setAssignment(mailbox,mailbox.assignment.manager,e.target.checked)); }}/>Automatic processing</label>}<div><strong>Mailbox grant:</strong> {mailbox.grant?.state??'not approved'}{mailbox.grant?.state==='reapproval_required'?<><p className="text-sm text-muted-foreground">Assignment alone does not authorize access. Review and approve this Mailbox grant separately.</p><Button disabled={busy||!online} onClick={()=>{ act(`${mailbox.mailboxId}:grant`,()=>mutations.reapprove(mailbox)); }}>Review and reapprove grant</Button></>:null}</div></CardContent></Card>}
