import * as React from 'react';
import { Alert,AlertDescription } from '@/components/heroui/alert.js';
import { Badge } from '@/components/heroui/badge.js';
import { Button } from '@/components/heroui/button.js';
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from '@/components/heroui/card.js';
import { Checkbox } from '@/components/heroui/checkbox.js';
import { Field } from '@/components/heroui/field.js';
import { Select, type SelectOption } from '@/components/heroui/select.js';
import { toast } from '@/components/heroui/toast.js';
import type { ManagerChoice,ManagerSettingsView,MailboxManagerView } from '../agent-connections/contracts.js';
const BUILT_IN_MANAGER_LABEL='Hypermail AI';
const key=(m:ManagerChoice)=>m.kind==='agent_connection'?`connection:${m.connectionId}`:m.kind;
const parse=(v:string):ManagerChoice=>v.startsWith('connection:')?{kind:'agent_connection',connectionId:v.slice(11)}:v==='none'?{kind:'none'}:{kind:'mastra'};
export type ManagerMutations={setDefault:(manager:ManagerChoice,revision:number)=>Promise<void>;setLifecycle:(id:string,state:'connected'|'paused'|'disconnected'|'security_revoked',revision:number)=>Promise<void>;setAssignment:(mailbox:MailboxManagerView,manager:ManagerChoice,automatic:boolean)=>Promise<void>;reapprove:(mailbox:MailboxManagerView)=>Promise<void>};
export function MailboxManagerSettings({settings,mutations,online=true}:{settings:ManagerSettingsView;mutations:ManagerMutations;online?:boolean}){const defaultManager=settings.defaultManager;const [busy,setBusy]=React.useState('');const act=(id:string,work:()=>Promise<void>)=>{if(!online){toast.warning('You are offline. No setting was changed; reconnect and try again.');return;}setBusy(id);void work().then(()=>{ toast.success('Manager settings updated.'); }).catch(()=>{ toast.danger('Settings changed or could not be saved. Reload and try again.'); }).finally(()=>{ setBusy(''); });};const choices=(none=true):SelectOption[]=>[...(none?[{value:'none',label:'None'}]:[]),{value:'mastra',label:BUILT_IN_MANAGER_LABEL},...settings.connections.map(c=>({value:`connection:${c.id}`,label:c.displayName}))];
 return <section aria-labelledby="manager-settings-title" className="grid gap-4"><header><h2 id="manager-settings-title" className="text-lg font-semibold">Mailbox Managers</h2><p className="text-sm text-muted-foreground">Assignment chooses who may manage a Mailbox. Grant approval separately authorizes capabilities. Unavailable work remains pending and has no fallback.</p></header>{defaultManager?<Card><CardHeader><CardTitle>Default for future Mailboxes</CardTitle><CardDescription>Changing this affects only Mailboxes added later. Existing assignments are not changed.</CardDescription></CardHeader><CardContent><Select aria-label="Default Mailbox Manager" value={key(defaultManager.manager)} disabled={!!busy||!online} onValueChange={selected=>{ act('default',()=>mutations.setDefault(parse(selected),defaultManager.revision)); }} options={choices(false)} /></CardContent></Card>:null}<div className="grid gap-3">{settings.mailboxes.map(mailbox=><MailboxCard key={mailbox.mailboxId} mailbox={mailbox} settings={settings} busy={!!busy} online={online} act={act} mutations={mutations}/>)}</div><section aria-labelledby="connections-title"><h3 id="connections-title" className="font-semibold">Agent Connections</h3><div className="mt-2 grid gap-2">{settings.connections.map(c=><Card key={c.id}><CardContent className="flex min-w-0 flex-row flex-wrap items-center justify-between gap-2"><div><strong>{c.displayName}</strong> <Badge variant="outline">{c.state}</Badge><p className="text-sm text-muted-foreground">Lifecycle revision {c.lifecycleRevision}</p></div><div className="flex flex-wrap gap-2">{c.state==='connected'?<Button variant="outline" disabled={!!busy||!online} onClick={()=>{ act(c.id,()=>mutations.setLifecycle(c.id,'paused',c.lifecycleRevision)); }}>Pause</Button>:c.state==='paused'||c.state==='disconnected'?<Button variant="outline" disabled={!!busy||!online} onClick={()=>{ act(c.id,()=>mutations.setLifecycle(c.id,'connected',c.lifecycleRevision)); }}>Resume</Button>:null}{c.state!=='security_revoked'?<Button variant="destructive" disabled={!!busy||!online} onClick={()=>{if(confirm('Security revoke this connection? Every Mailbox grant will require explicit reapproval.'))act(c.id,()=>mutations.setLifecycle(c.id,'security_revoked',c.lifecycleRevision));}}>Security revoke</Button>:<Alert><AlertDescription>Security revoked. A verified reconnect is required, then every Mailbox grant must be reapproved.</AlertDescription></Alert>}</div></CardContent></Card>)}</div></section></section>;
}
function MailboxCard({mailbox,settings,busy,online,act,mutations}:{mailbox:MailboxManagerView;settings:ManagerSettingsView;busy:boolean;online:boolean;act:(id:string,w:()=>Promise<void>)=>void;mutations:ManagerMutations}) {
  const [choice,setChoice]=React.useState(key(mailbox.assignment.manager));
  const automatic=mailbox.assignment.automaticProcessingEnabled;
  const changed=choice!==key(mailbox.assignment.manager);
  const managerId=`mailbox-manager-${mailbox.mailboxId}`;
  const automaticId=`mailbox-automatic-${mailbox.mailboxId}`;
  return <Card><CardHeader><CardTitle>{mailbox.mailboxLabel}</CardTitle><CardDescription>Manager assignment revision {mailbox.assignment.revision}</CardDescription></CardHeader><CardContent className="grid gap-3">
    <Field><Select id={managerId} label="Assigned Manager" value={choice} disabled={busy||!online} onValueChange={setChoice} options={[{value:'none',label:'None'},{value:'mastra',label:BUILT_IN_MANAGER_LABEL},...settings.connections.map(c=>({value:`connection:${c.id}`,label:c.displayName}))]} /></Field>
    {changed?<Button disabled={busy||!online} onClick={()=>{ act(mailbox.mailboxId,()=>mutations.setAssignment(mailbox,parse(choice),false)); }}>Confirm assignment change</Button>:<Field><Checkbox id={automaticId} label="Automatic processing" isSelected={automatic} isDisabled={busy||!online||mailbox.grant?.state!=='active'||mailbox.assignment.manager.kind==='none'} onChange={(selected:boolean)=>{ act(mailbox.mailboxId,()=>mutations.setAssignment(mailbox,mailbox.assignment.manager,selected)); }}/></Field>}
    <div><strong>Mailbox grant:</strong> {mailbox.grant?.state??'not approved'}{mailbox.grant?.state==='reapproval_required'?<><p className="text-sm text-muted-foreground">Assignment alone does not authorize access. Review and approve this Mailbox grant separately.</p><Button disabled={busy||!online} onClick={()=>{ act(`${mailbox.mailboxId}:grant`,()=>mutations.reapprove(mailbox)); }}>Review and reapprove grant</Button></>:null}</div>
  </CardContent></Card>;
}
