/* eslint-disable @typescript-eslint/unbound-method */
import {describe,expect,it,vi} from 'vitest';
import {AgentConnectionsService,createAgentConnectionRoutes,type AgentConnectionsRepository} from '../../src/agent-connections/index.js';
const user='11111111-1111-4111-8111-111111111111',connection='22222222-2222-4222-8222-222222222222',mailbox='33333333-3333-4333-8333-333333333333';
const view={onboardingRequired:false,defaultManager:{manager:{kind:'mastra' as const},revision:2},connections:[],mailboxes:[]};
const repository=():AgentConnectionsRepository=>({read:vi.fn(()=>Promise.resolve(view)),setDefault:vi.fn(()=>Promise.resolve()),setLifecycle:vi.fn(()=>Promise.resolve()),setAssignment:vi.fn(()=>Promise.resolve()),reapproveGrant:vi.fn(()=>Promise.resolve())});
const request=(body:Record<string,unknown>={},origin:string|null='https://mail.test')=>({method:'POST',origin,auth:{subjectId:user},body});
describe('Agent Connection settings routes',()=>{
 it('rejects cross-origin mutations and requires optimistic revisions',async()=>{const repo=repository(),routes=createAgentConnectionRoutes(new AgentConnectionsService(repo),'https://mail.test');expect(await routes.setDefault(request({manager:{kind:'mastra'},expectedRevision:2},'https://evil.test'))).toMatchObject({status:403});expect(repo.setDefault).not.toHaveBeenCalled();expect(await routes.setDefault(request({manager:{kind:'mastra'},expectedRevision:0}))).toMatchObject({status:400});});
 it('changes only the future-mailbox default',async()=>{const repo=repository(),routes=createAgentConnectionRoutes(new AgentConnectionsService(repo),'https://mail.test');expect(await routes.setDefault(request({manager:{kind:'agent_connection',connectionId:connection},expectedRevision:2}))).toMatchObject({status:200});expect(repo.setDefault).toHaveBeenCalledWith(user,{kind:'agent_connection',connectionId:connection},2);expect(repo.setAssignment).not.toHaveBeenCalled();});
 it('keeps assignment and grant reapproval as distinct calls',async()=>{const repo=repository(),routes=createAgentConnectionRoutes(new AgentConnectionsService(repo),'https://mail.test');await routes.assignment(request({manager:{kind:'agent_connection',connectionId:connection},automaticProcessingEnabled:false,expectedAssignmentRevision:3,expectedGrantRevision:4}),mailbox);expect(repo.setAssignment).toHaveBeenCalled();expect(repo.reapproveGrant).not.toHaveBeenCalled();await routes.reapprove(request({expectedGrantRevision:5,idempotencyKey:'approval-123'}),mailbox);expect(repo.reapproveGrant).toHaveBeenCalledWith(user,mailbox,5,'approval-123',expect.any(String));});
 it('uses a dedicated security revoke and never permits None as the default',async()=>{const repo=repository(),routes=createAgentConnectionRoutes(new AgentConnectionsService(repo),'https://mail.test');expect(await routes.setDefault(request({manager:{kind:'none'},expectedRevision:2}))).toMatchObject({status:400});await routes.securityRevoke(request({expectedRevision:7}),connection);expect(repo.setLifecycle).toHaveBeenCalledWith(user,connection,'security_revoked',7);});
});
