/* eslint-disable @typescript-eslint/no-non-null-assertion, @typescript-eslint/no-unnecessary-type-assertion */
import type { Sql } from 'postgres';
import type { Message } from '@hypermail/hypermail';
import type { TenantHypermailClientBundle, TenantHypermailSessionProvider } from '@hypermail/hypermail';
import { PublicMcpError, type TenantAuthority, type TenantMailboxOperations } from './core.js';
import type { PostgresMcpMutationJournal } from './postgres-mutation-journal.js';
import type { PublicToolArgs, PublicToolResult } from './contracts.js';
type Identity={email:string}; type Mapped={id:string;provider_message_id:string;folder_id:string|null};
const ABSOLUTE_ATTACHMENT_BYTES = 25_000_000;
const DEFAULT_ATTACHMENT_BYTES = 4 * 1024 * 1024;
class AttachmentByteSemaphore {
 private used=0; private readonly waiting:{weight:number;signal?:AbortSignal;resolve:(release:()=>void)=>void;reject:(error:Error)=>void;abort?:()=>void}[]=[];
 constructor(private readonly maximum:number,private readonly changed?:(used:number)=>void){}
 acquire(weight:number,signal?:AbortSignal):Promise<()=>void>{if(weight>this.maximum)return Promise.reject(new PublicMcpError('temporarily_unavailable'));if(signal?.aborted)return Promise.reject(new PublicMcpError('temporarily_unavailable'));return new Promise((resolve,reject)=>{const waiter={weight,...(signal?{signal}:{}),resolve,reject} as (typeof this.waiting)[number];if(signal){waiter.abort=()=>{const index=this.waiting.indexOf(waiter);if(index>=0)this.waiting.splice(index,1);reject(new PublicMcpError('temporarily_unavailable'))};signal.addEventListener('abort',waiter.abort,{once:true})}this.waiting.push(waiter);this.drain()})}
 private drain(){for(let i=0;i<this.waiting.length;){const waiter=this.waiting[i]!;if(this.used+waiter.weight>this.maximum){i++;continue}this.waiting.splice(i,1);if(waiter.abort)waiter.signal?.removeEventListener('abort',waiter.abort);this.used+=waiter.weight;this.changed?.(this.used);let released=false;waiter.resolve(()=>{if(released)return;released=true;this.used-=waiter.weight;this.changed?.(this.used);this.drain()})}}
}
type AttachmentLimits={tempDirectory:string;maxBytes:number;maxEncodedBytes?:number;globalMaxEncodedBytes?:number;onReservationChange?:(used:number)=>void};

export class TenantRoutedMailboxAdapter implements TenantMailboxOperations {
 private readonly attachments:AttachmentLimits;private readonly encodedLimit:number;private readonly attachmentBytes:AttachmentByteSemaphore;
 constructor(private readonly sql:Sql,private readonly sessions:TenantHypermailSessionProvider,private readonly finalFence:(authority:TenantAuthority,capability:string)=>Promise<boolean>,attachments:AttachmentLimits={tempDirectory:'/not-configured',maxBytes:DEFAULT_ATTACHMENT_BYTES},private readonly journal?:PostgresMcpMutationJournal){const maxBytes=Math.min(attachments.maxBytes,DEFAULT_ATTACHMENT_BYTES,ABSOLUTE_ATTACHMENT_BYTES);this.encodedLimit=Math.min(attachments.maxEncodedBytes??4*Math.ceil(maxBytes/3),4*Math.ceil(ABSOLUTE_ATTACHMENT_BYTES/3));this.attachments={...attachments,maxBytes};this.attachmentBytes=new AttachmentByteSemaphore(attachments.globalMaxEncodedBytes??this.encodedLimit*2,attachments.onReservationChange)}
 private async withBundle<T>(a:TenantAuthority,operation:(bundle:TenantHypermailClientBundle)=>Promise<T>):Promise<T>{const lease=await this.sessions.leaseForUser(a.userId);try{return await operation(lease.bundle)}finally{await lease.release()}}
 private async identity(a:TenantAuthority):Promise<Identity>{const rows=await this.sql<Identity[]>`select ac.email from app.accounts ac join app.user_accounts ua on ua.account_id=ac.id where ua.user_id=${a.userId} and ua.account_id=${a.mailboxId}`;if(!rows[0])throw new PublicMcpError('forbidden');return rows[0]}
 private async providerMessage(a:TenantAuthority,id:string):Promise<string>{const rows=await this.sql<{provider_message_id:string}[]>`select m.provider_message_id from app.messages m join app.user_accounts ua on ua.account_id=m.account_id where m.id=${id} and m.account_id=${a.mailboxId} and ua.user_id=${a.userId} and m.deleted_at is null`;if(!rows[0])throw new PublicMcpError('not_found');return rows[0].provider_message_id}
 private async providerFolder(a:TenantAuthority,id:string):Promise<string>{const rows=await this.sql<{provider_folder_id:string}[]>`select f.provider_folder_id from app.folders f join app.user_accounts ua on ua.account_id=f.account_id where f.id=${id} and f.account_id=${a.mailboxId} and ua.user_id=${a.userId}`;if(!rows[0])throw new PublicMcpError('not_found');return rows[0].provider_folder_id}
 private async project(a:TenantAuthority,messages:readonly Message[]):Promise<PublicToolResult<'list_emails'>['messages']>{if(!messages.length)return[];const rows=await this.sql<Mapped[]>`select id,provider_message_id,folder_id from app.messages where account_id=${a.mailboxId} and provider_message_id=any(${messages.map(m=>m.id)}) and deleted_at is null`;const by=new Map(rows.map(r=>[r.provider_message_id,r]));return messages.map(m=>{const x=by.get(m.id);if(!x)throw new PublicMcpError('temporarily_unavailable');return{id:x.id,...(m.subject===undefined?{}:{subject:m.subject}),...(m.from?{from:m.from}:{}),...(m.receivedAt?{receivedAt:m.receivedAt}:{}),...(m.isRead===undefined?{}:{isRead:m.isRead}),...(x.folder_id?{folderId:x.folder_id}:{}),hasAttachments:(m.attachments?.length??0)>0}})}
 async list(a:TenantAuthority,args:PublicToolArgs<'list_emails'>){const account=await this.identity(a);const folder=args.folderId?await this.providerFolder(a,args.folderId):undefined;if(args.cursor&&folder)throw new PublicMcpError('invalid_request');return this.withBundle(a,async bundle=>{const page=folder?await bundle.read.mailboxPage(account.email,{folder,...(args.limit===undefined?{}:{limit:args.limit})}):await bundle.read.inbox({account:account.email,...(args.cursor?{cursor:args.cursor}:{}),...(args.limit===undefined?{}:{limit:args.limit})});return{messages:await this.project(a,page.messages),...('cursor' in page&&page.cursor?{nextCursor:page.cursor}:{})}})}
 async search(a:TenantAuthority,args:PublicToolArgs<'search_emails'>){const account=await this.identity(a);return this.withBundle(a,async bundle=>{const items=await bundle.read.search({account:account.email,query:args.query,...(args.from?{from:args.from}:{}),...(args.to?{to:args.to}:{}),...(args.limit===undefined?{}:{limit:args.limit})});return{messages:await this.project(a,items)}})}
 async read(a:TenantAuthority,args:PublicToolArgs<'read_email'>){const account=await this.identity(a),id=await this.providerMessage(a,args.messageId);return this.withBundle(a,async bundle=>{const m=await bundle.read.readMessage(account.email,id,args.format);const summary=(await this.project(a,[m]))[0];if(!summary)throw new PublicMcpError('not_found');return{...summary,...(m.to?{to:m.to}:{}),...(m.cc?{cc:m.cc}:{}),body:m.body??'',bodyFormat:(m.bodyFormat==='text'?'text':'markdown') as 'text'|'markdown',attachments:await this.projectAttachments(a,args.messageId,m.attachments??[])}})}
 private async projectAttachments(a:TenantAuthority,messageId:string,items:readonly {id:string;name:string;contentType?:string;size?:number}[]){if(!items.length)return[];const rows=await this.sql<{id:string;provider_attachment_id:string}[]>`select at.id,at.provider_attachment_id from app.attachments at join app.messages m on m.id=at.message_id where m.id=${messageId} and m.account_id=${a.mailboxId} and at.provider_attachment_id=any(${items.map(x=>x.id)})`;const by=new Map(rows.map(r=>[r.provider_attachment_id,r.id]));return items.map(x=>{const id=by.get(x.id);if(!id)throw new PublicMcpError('temporarily_unavailable');return{id,name:x.name,...(x.contentType?{contentType:x.contentType}:{}),...(x.size===undefined?{}:{size:x.size})}})}
 async listFolders(a:TenantAuthority){const account=await this.identity(a);return this.withBundle(a,async bundle=>{const items=await bundle.read.folders(account.email);const rows=await this.sql<{id:string;provider_folder_id:string;parent_provider_folder_id:string|null}[]>`select id,provider_folder_id,parent_provider_folder_id from app.folders where account_id=${a.mailboxId}`;const by=new Map(rows.map(r=>[r.provider_folder_id,r]));return{folders:items.map(f=>{const x=by.get(f.id);if(!x)throw new PublicMcpError('temporarily_unavailable');const parent=x.parent_provider_folder_id?by.get(x.parent_provider_folder_id)?.id:undefined;return{id:x.id,displayName:f.displayName,...(parent?{parentFolderId:parent}:{})}})}})}
 async readAttachment(a:TenantAuthority,x:PublicToolArgs<'read_attachment'>):Promise<PublicToolResult<'read_attachment'>>{const account=await this.identity(a),message=await this.providerMessage(a,x.messageId);const rows=await this.sql<{provider_attachment_id:string;filename:string;media_type:string;size_bytes:number}[]>`select at.provider_attachment_id,at.filename,at.media_type,at.size_bytes from app.attachments at join app.messages m on m.id=at.message_id where at.id=${x.attachmentId} and m.id=${x.messageId} and m.account_id=${a.mailboxId}`;const item=rows[0];if(!item)throw new PublicMcpError('not_found');if(item.size_bytes>this.attachments.maxBytes||item.size_bytes>ABSOLUTE_ATTACHMENT_BYTES||4*Math.ceil(item.size_bytes/3)>this.encodedLimit)throw new PublicMcpError('invalid_request');const releaseBytes=await this.attachmentBytes.acquire(this.encodedLimit,a.signal);let handedToResponse=false;const releaseOnAbort=()=>{releaseBytes()};a.signal?.addEventListener('abort',releaseOnAbort,{once:true});if(a.signal?.aborted)releaseOnAbort();try{const result=await this.withBundle(a,async bundle=>{const opened=await bundle.read.openAttachment(account.email,message,item.provider_attachment_id,{tempDirectory:this.attachments.tempDirectory,maxBytes:this.attachments.maxBytes,...(a.signal?{signal:a.signal}:{})});let content='',remainder=Buffer.alloc(0),seen=0;try{for await(const raw of opened.stream){if(a.signal?.aborted)throw new PublicMcpError('temporarily_unavailable');const chunk=Buffer.from(raw);seen+=chunk.length;if(seen>this.attachments.maxBytes||seen>ABSOLUTE_ATTACHMENT_BYTES)throw new RangeError('attachment too large');const combined=remainder.length?Buffer.concat([remainder,chunk]):chunk;const complete=combined.length-combined.length%3;if(complete)content+=combined.subarray(0,complete).toString('base64');remainder=Buffer.from(combined.subarray(complete));if(content.length>this.encodedLimit)throw new RangeError('attachment encoded response too large')}if(remainder.length)content+=remainder.toString('base64');if(content.length>this.encodedLimit)throw new RangeError('attachment encoded response too large')}finally{await opened.cleanup()}return{id:x.attachmentId,name:item.filename,contentType:item.media_type,size:seen,encoding:'base64' as const,content}});handedToResponse=!!a.signal;return result}finally{if(!handedToResponse){a.signal?.removeEventListener('abort',releaseOnAbort);releaseBytes()}}}
 private async mutate(a:TenantAuthority,messageId:string,kind:'archive'|'trash'|'read'|'unread'){const account=await this.identity(a),id=await this.providerMessage(a,messageId);return this.withBundle(a,async bundle=>{const actionKind=kind==='archive'?'archive':kind==='trash'?'recoverable_trash':kind==='read'?'mark_read':'mark_unread';const journal=this.journal?await this.journal.prepare(a,actionKind,{messageId}):undefined;if(journal)await this.journal!.start(journal);if(!await this.finalFence(a,kind==='archive'?'mail.archive':kind==='trash'?'mail.trash_recoverable':kind==='read'?'mail.mark_read':'mail.mark_unread')){if(journal)await this.journal!.cancel(journal);throw new PublicMcpError('forbidden')}try{const receipt=await(kind==='archive'?bundle.policy.archive(account.email,id):kind==='trash'?bundle.policy.trash(account.email,id):bundle.policy.mark(account.email,id,kind==='read'));if(journal)await this.journal!.verifying(journal);let observed=false;if(kind==='read'||kind==='unread')observed=(await bundle.read.readMessage(account.email,id,'text')).isRead===(kind==='read');else{const folders=await bundle.read.folders(account.email);const wanted=folders.find(f=>kind==='archive'?f.wellKnownName?.toLowerCase()==='archive':['deleteditems','trash'].includes(f.wellKnownName?.toLowerCase()??''));observed=!!wanted&&await bundle.policy.containsMessageInFolder(account.email,receipt.id,wanted.id)}if(journal){if(observed)await this.journal!.verified(journal,{kind,messageId,observed},receipt.id);else await this.journal!.finish(journal,'unverifiable')}if(!observed)throw new PublicMcpError('temporarily_unavailable');return{messageId,status:kind==='trash'?'trashed_recoverable':kind==='archive'?'archived':kind} as const}catch(error){if(journal)await this.journal!.finish(journal,'unverifiable');throw error}})}
 archive(a:TenantAuthority,x:PublicToolArgs<'archive_email'>){return this.mutate(a,x.messageId,'archive')}
 trashRecoverable(a:TenantAuthority,x:PublicToolArgs<'trash_email'>){return this.mutate(a,x.messageId,'trash')}
 markRead(a:TenantAuthority,x:PublicToolArgs<'mark_read'>){return this.mutate(a,x.messageId,'read')}
 markUnread(a:TenantAuthority,x:PublicToolArgs<'mark_unread'>){return this.mutate(a,x.messageId,'unread')}
 async move(a:TenantAuthority,x:PublicToolArgs<'move_email'>){const account=await this.identity(a),id=await this.providerMessage(a,x.messageId),folder=await this.providerFolder(a,x.destinationFolderId);return this.withBundle(a,async bundle=>{const journal=this.journal?await this.journal.prepare(a,'move',{messageId:x.messageId,destinationFolderId:x.destinationFolderId}):undefined;if(journal)await this.journal!.start(journal);if(!await this.finalFence(a,'mail.move')){if(journal)await this.journal!.cancel(journal);throw new PublicMcpError('forbidden')}try{const receipt=await bundle.policy.move(account.email,id,folder);if(journal)await this.journal!.verifying(journal);const observed=await bundle.policy.containsMessageInFolder(account.email,receipt.id,folder);if(journal){if(observed)await this.journal!.verified(journal,{messageId:x.messageId,destinationFolderId:x.destinationFolderId,observed},receipt.id);else await this.journal!.finish(journal,'unverifiable')}if(!observed)throw new PublicMcpError('temporarily_unavailable');return{messageId:x.messageId,status:'moved' as const}}catch(error){if(journal)await this.journal!.finish(journal,'unverifiable');throw error}})}
}
