/* eslint-disable @typescript-eslint/no-unnecessary-type-assertion */
import type { DraftService } from '../drafts/service.js';
import type { TenantAuthority, TenantDraftOperations } from './core.js';
import type { PostgresMcpMutationJournal } from './postgres-mutation-journal.js';
import { PublicMcpError } from './core.js';
import type { PublicToolArgs } from './contracts.js';
const scope=(a:TenantAuthority)=>({subjectId:a.userId,accountIds:[a.mailboxId]});
const recipients=(x:{to?:readonly {address:string}[]|undefined;cc?:readonly {address:string}[]|undefined;bcc?:readonly {address:string}[]|undefined})=>[...(x.to??[]).map(r=>({kind:'to' as const,address:r.address})),...(x.cc??[]).map(r=>({kind:'cc' as const,address:r.address})),...(x.bcc??[]).map(r=>({kind:'bcc' as const,address:r.address}))];
export class TenantDraftServiceAdapter implements TenantDraftOperations{
 constructor(private readonly drafts:DraftService,private readonly fence:(a:TenantAuthority,c:string)=>Promise<boolean>,private readonly journal:PostgresMcpMutationJournal){}
 async create(a:TenantAuthority,x:PublicToolArgs<'draft_email'>){const journal=await this.journal.prepare(a,'draft_create',{requestId:a.authorizationDecisionId});await this.journal.start(journal);if(!await this.fence(a,'draft.create')){await this.journal.cancel(journal);throw new PublicMcpError('forbidden')}try{const d=await this.drafts.agentDraftWriter.createAgent(scope(a),{accountId:a.mailboxId,recipients:recipients(x),subject:x.subject,body:x.body,bodyFormat:'markdown'});await this.journal.verifying(journal);await this.journal.verified(journal,{draftId:d.id,version:d.version,state:d.state});return{draftId:d.id,version:d.version,state:(d.state==='ready'?'ready':'editing') as 'ready'|'editing'}}catch(error){await this.journal.finish(journal,'unverifiable');throw error}}
 async edit(a:TenantAuthority,x:PublicToolArgs<'edit_draft'>){const s=scope(a),current=await this.drafts.detail(s,x.draftId);if(current.createdBy!=='agent')throw new Error('DraftNotFoundError');const journal=await this.journal.prepare(a,'draft_edit',{draftId:x.draftId,expectedVersion:String(x.expectedVersion)});await this.journal.start(journal);if(!await this.fence(a,'draft.edit')){await this.journal.cancel(journal);throw new PublicMcpError('forbidden')}try{const d=await this.drafts.agentDraftWriter.editAgent(s,x.draftId,x.expectedVersion,{recipients:('to'in x||'cc'in x||'bcc'in x)?recipients({to:x.to??current.recipients.filter(r=>r.kind==='to').map(r=>({address:r.address})),cc:x.cc??current.recipients.filter(r=>r.kind==='cc').map(r=>({address:r.address})),bcc:x.bcc??current.recipients.filter(r=>r.kind==='bcc').map(r=>({address:r.address}))}):current.recipients,subject:x.subject??current.subject,body:x.body??current.body,bodyFormat:'markdown'});await this.journal.verifying(journal);await this.journal.verified(journal,{draftId:d.id,version:d.version,state:d.state});return{draftId:d.id,version:d.version,state:(d.state==='ready'?'ready':'editing') as 'ready'|'editing'}}catch(error){await this.journal.finish(journal,'unverifiable');throw error}}
}