import { describe, expect, it } from 'vitest';
import { PUBLIC_AGENT_TOOL_CAPABILITY, authorizeAgentTool, authorizeAuditedFreshInvocation, executeAuthorizedMutation, publicAgentToolNames } from '../src/index.js';
const userId='11111111-1111-4111-8111-111111111111', connectionId='22222222-2222-4222-8222-222222222222', mailboxId='33333333-3333-4333-8333-333333333333';
const now='2026-08-13T12:00:00.000Z'; const capabilities=[...new Set(Object.values(PUBLIC_AGENT_TOOL_CAPABILITY))];
const loaded=()=>({ facts:{ expectedAudience:'https://hypermail.example/mcp', requiredScope:'agent:mailbox', connection:{id:connectionId,userId,state:'connected' as const,lifecycleRevision:3}, mailbox:{id:mailboxId,userId}, assignment:{id:'44444444-4444-4444-8444-444444444444',userId,mailboxId,manager:{kind:'agent_connection' as const,connectionId},automaticProcessingEnabled:true,revision:4,createdAt:now,updatedAt:now}, grant:{id:'55555555-5555-4555-8555-555555555555',userId,mailboxId,manager:{kind:'agent_connection' as const,connectionId},capabilities,invocationModes:['interactive','automatic'] as const,state:'active' as const,revision:5,approvedAt:now,createdAt:now,updatedAt:now}, safetyCeiling:{revision:6,capabilities,invocationModes:['interactive','automatic'] as const},tool:'read_email' as const }, binding:{sessionId:'verified-session-123456',mode:'interactive' as const,principal:{valid:true,audience:'https://hypermail.example/mcp',scopes:['agent:mailbox'],subject:{kind:'agent_connection' as const,userId,connectionId},mailboxId,lifecycleRevision:3,assignmentRevision:4,grantRevision:5,safetyRevision:6}} });
describe('Agent Connection authorization contracts',()=>{
 it('keeps the explicit safe tool/capability set in parity',()=>{expect(Object.keys(PUBLIC_AGENT_TOOL_CAPABILITY)).toEqual(publicAgentToolNames);expect(PUBLIC_AGENT_TOOL_CAPABILITY.request_send_email).toBe('send.request');for(const name of ['send_email','send_draft','delete_email','remove_account','create_folder'])expect(name in PUBLIC_AGENT_TOOL_CAPABILITY).toBe(false);});
 it('binds authority to verified principal mailbox and session mode',()=>{const x=loaded();expect(authorizeAgentTool(x.facts,x.binding)).toMatchObject({allowed:true,authority:{mailboxId,mode:'interactive'}});x.binding.principal.mailboxId='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';expect(authorizeAgentTool(x.facts,x.binding)).toEqual({allowed:false,code:'mailbox_subject_mismatch'});});
 it('does not accept invocation mode in caller-controlled authorization facts',()=>{const x=loaded();const raw={...x.facts,mode:'automatic'};expect(authorizeAgentTool(raw as never,x.binding)).toEqual({allowed:false,code:'invalid_request'});});
 it.each([['invalid_token',(x:ReturnType<typeof loaded>)=>{x.binding.principal.valid=false;}],['invalid_audience',(x:ReturnType<typeof loaded>)=>{x.binding.principal.audience='other';}],['connection_inactive',(x:ReturnType<typeof loaded>)=>{x.facts.connection.state='paused';}],['stale_lifecycle_revision',(x:ReturnType<typeof loaded>)=>{x.facts.connection.lifecycleRevision++;}],['stale_assignment_revision',(x:ReturnType<typeof loaded>)=>{x.facts.assignment.revision++;}],['grant_inactive',(x:ReturnType<typeof loaded>)=>{x.facts.grant.state='revoked';}],['stale_grant_revision',(x:ReturnType<typeof loaded>)=>{x.facts.grant.revision++;}],['stale_safety_revision',(x:ReturnType<typeof loaded>)=>{x.facts.safetyCeiling.revision++;}],['capability_denied',(x:ReturnType<typeof loaded>)=>{x.facts.grant.capabilities=['mail.list'];}]] as const)('denies %s',(code,mutate)=>{const x=loaded();mutate(x);expect(authorizeAgentTool(x.facts,x.binding)).toEqual({allowed:false,code});});
 it('derives bounded audit identity and mode from the verified binding',async()=>{const events:unknown[]=[];const x=loaded();const result=await authorizeAuditedFreshInvocation({loader:{load:()=>Promise.resolve(x)},audit:{record:event=>{events.push(event);return Promise.resolve();}},request:{tool:'read_email'},decisionId:'decision-12345678',now:()=>new Date(now)});expect(result.decision.allowed).toBe(true);expect(events).toMatchObject([{userId,connectionId,mailboxId,mode:'interactive',tool:'read_email',code:'allowed'}]);expect(JSON.stringify(events)).not.toContain('scopes');});
 it('separates initial authorization from an executor-owned final mutation fence',async()=>{const order:string[]=[];const x=loaded();const initial=await authorizeAuditedFreshInvocation({loader:{load:()=>Promise.resolve(x)},audit:{record:()=>Promise.resolve()},request:{tool:'read_email'},decisionId:'decision-12345678'});const result=await executeAuthorizedMutation(initial,{stillCurrent:()=>{order.push('fence');return Promise.resolve(true);}},()=>{order.push('mutate');return Promise.resolve('done');});expect(result).toBe('done');expect(order).toEqual(['fence','mutate']);const stale=await executeAuthorizedMutation(initial,{stillCurrent:()=>Promise.resolve(false)},()=>Promise.reject(new Error('must not run')));expect(stale).toEqual({allowed:false,code:'stale_final_fence'});});
});
