/* eslint-disable @typescript-eslint/require-await, @typescript-eslint/unbound-method */
import { describe, expect, it, vi } from 'vitest';
import { PublicMcpError, PublicMcpFacadeCore, mapPublicMcpError, publicToolContracts, publicToolRegistry, PUBLIC_MCP_RESOURCE_PATH, type PublicFacadePorts } from '../../src/mcp/index.js';
const userId='11111111-1111-4111-8111-111111111111',connectionId='22222222-2222-4222-8222-222222222222',mailboxId='33333333-3333-4333-8333-333333333333';
const binding={sessionId:'verified-session-123456',mode:'interactive' as const,principal:{userId,connectionId,mailboxId,audience:'https://example.test/mcp',scopes:['agent:mailbox'],lifecycleRevision:1,assignmentRevision:2,grantRevision:3,safetyRevision:4}};
const authority={userId,connectionId,mailboxId,mode:'interactive' as const,lifecycleRevision:1,assignmentRevision:2,grantRevision:3,safetyRevision:4};
const pending={requestId:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',draftId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',state:'pending_owner_approval' as const,expiresAt:'2026-08-13T12:00:00.000Z'};
function ports(order:string[]=[]):PublicFacadePorts{return {authorizer:{authorize:async(received,tool)=>{order.push('authorize');expect(received).toBe(binding);return {authority:{...authority,mode:received.mode},decisionId:`d-${tool}`};}},fence:{stillCurrent:async()=>{order.push('fence');return true;}},mailbox:{list:async()=>({messages:[]}),search:async()=>({messages:[]}),read:vi.fn(),readAttachment:vi.fn(),listFolders:async()=>({folders:[]}),archive:vi.fn(),trashRecoverable:vi.fn(),move:vi.fn(),markRead:vi.fn(),markUnread:vi.fn()},drafts:{create:async()=>({draftId:pending.draftId,version:1,state:'editing'}),edit:vi.fn()},sendRequests:{requestPending:async(a,args)=>{order.push('requestPending');expect(a.mailboxId).toBe(mailboxId);expect(args).not.toHaveProperty('mailboxId');return pending;}}};}
describe('public MCP contract',()=>{
 it('exposes exactly 13 explicit tools with SDK annotations and /mcp resource',()=>{expect(Object.keys(publicToolRegistry)).toEqual(['list_emails','search_emails','read_email','read_attachment','list_folders','archive_email','trash_email','move_email','mark_read','mark_unread','draft_email','edit_draft','request_send_email']);expect(PUBLIC_MCP_RESOURCE_PATH).toBe('/mcp');expect(publicToolRegistry.list_emails.annotations).toMatchObject({readOnlyHint:true,openWorldHint:false});expect(publicToolRegistry.trash_email.annotations).toMatchObject({destructiveHint:true});expect(publicToolRegistry.request_send_email.description).toContain('never sends');});
 it('makes every input and result strict and rejects tenant/account/email/user/connection keys',()=>{for(const [name,contract] of Object.entries(publicToolContracts)){expect(contract.args.safeParse({mailboxId}).success,`${name}: mailboxId`).toBe(false);expect(contract.args.safeParse({account:'victim@example.test'}).success,`${name}: account`).toBe(false);expect(contract.args.safeParse({userId,connectionId}).success,`${name}: identity`).toBe(false);expect(contract.result.safeParse({secret:'provider-token'}).success,`${name}: result strict`).toBe(false);}});
 it('enforces important bounds',()=>{expect(publicToolContracts.list_emails.args.safeParse({limit:101}).success).toBe(false);expect(publicToolContracts.search_emails.args.safeParse({query:'x'.repeat(501)}).success).toBe(false);expect(publicToolContracts.read_attachment.result.safeParse({id:'a',name:'x',encoding:'base64',content:'x'.repeat(33_333_337)}).success).toBe(false);expect(publicToolContracts.draft_email.args.safeParse({to:[{address:'not-email'}],subject:'s',body:'b'}).success).toBe(false);});
 it('injects verified authority and fences immediately before mutations',async()=>{const order:string[]=[];const p=ports(order);p.mailbox.archive=async(a,args)=>{order.push('archive');expect(a).toMatchObject({userId,connectionId,mailboxId,mode:'interactive'});expect(args).toEqual({messageId:'provider-id'});return {messageId:'provider-id',status:'archived'};};const result=await new PublicMcpFacadeCore(p).invoke(binding,'archive_email',{messageId:'provider-id'});expect(result.status).toBe('archived');expect(order).toEqual(['authorize','fence','archive']);});
 it('does not fence reads',async()=>{const order:string[]=[];await new PublicMcpFacadeCore(ports(order)).invoke(binding,'list_emails',{});expect(order).toEqual(['authorize']);});
 it('fails closed before mutation when final fence is stale',async()=>{const p=ports();p.fence.stillCurrent=async()=>false;p.mailbox.archive=vi.fn();await expect(new PublicMcpFacadeCore(p).invoke(binding,'archive_email',{messageId:'x'})).rejects.toMatchObject({code:'forbidden'});expect(p.mailbox.archive).not.toHaveBeenCalled();});
 it('request_send only creates pending owner approval and has no send port',async()=>{const order:string[]=[];const p=ports(order);expect('send' in p.sendRequests).toBe(false);const result=await new PublicMcpFacadeCore(p).invoke(binding,'request_send_email',{draftId:pending.draftId,expectedVersion:1});expect(result.state).toBe('pending_owner_approval');expect(order).toEqual(['authorize','fence','requestPending']);});
 it('maps errors to stable redacted messages',()=>{const raw=new Error('access_token=secret victim@example.test provider dump');const mapped=mapPublicMcpError(raw);expect(mapped).toEqual(expect.objectContaining({code:'internal_error',message:'The operation failed.'}));expect(JSON.stringify(mapped)).not.toContain('secret');expect(mapPublicMcpError(new TypeError('private'))).toEqual(expect.objectContaining({code:'invalid_request'}));expect(mapPublicMcpError(new PublicMcpError('conflict')).message).toBe('The resource changed; refresh and retry.');});
});
