import { createHash } from 'node:crypto';
import { PrivateApprovedSendError, type AuthoritativeMailSendProvider, type ProviderSendStatus } from '@hypermail/send';
export interface TenantAuthoritativeMailSendProvider { providerForUser(userId: string): AuthoritativeMailSendProvider; }
import type { OwnerSendScope } from './contracts.js';
import type { OwnerSendRequest } from './contracts.js';
import { SendRequestFreshAuthError } from './contracts.js';
import type { PostgresOwnerSendRequestRepository } from './postgres-repository.js';
const FRESH=5*60_000;
const reasonCode=(value:string)=>/^[a-z][a-z0-9_]{0,99}$/.test(value)?value:'provider_rejected';
const digest=(status:Extract<ProviderSendStatus,{state:'verified'}>)=>createHash('sha256').update(JSON.stringify({providerMessageId:status.providerMessageId,observedAt:status.observedAt,evidence:status.evidence})).digest('hex');
export class OwnerSendRequestService {
 constructor(private readonly repository:PostgresOwnerSendRequestRepository,private readonly provider:AuthoritativeMailSendProvider|TenantAuthoritativeMailSendProvider,private readonly now:()=>Date=()=>new Date()){}
 list(scope:OwnerSendScope){return this.repository.list(scope)} detail(scope:OwnerSendScope,id:string){return this.repository.detail(scope,id)} reject(scope:OwnerSendScope,id:string){return this.repository.reject(scope,id)}
 begin(scope:OwnerSendScope,id:string,expected:number,confirmation:string){this.fresh(scope);return this.repository.begin(scope,id,expected,confirmation)}
 async confirm(scope:OwnerSendScope,id:string,approvalId:string,confirmation:string):Promise<OwnerSendRequest>{this.fresh(scope);const provider='providerForUser' in this.provider?this.provider.providerForUser(scope.subjectId):this.provider;const claimed=await this.repository.claim(scope,id,approvalId,confirmation);if(!('message' in claimed))return claimed;let report;try{report=await provider.send({approvalId:claimed.approvalId,accountId:claimed.message.accountId,draftId:claimed.message.draftId,draftVersion:claimed.message.draftVersion,idempotencyKey:claimed.idempotencyKey,recipients:claimed.message.recipients,subject:claimed.message.subject,body:claimed.message.body})}catch(error){return this.repository.finish(scope,id,error instanceof PrivateApprovedSendError&&error.definiteRejection?{kind:'failed',reason:'provider_rejected'}:{kind:'unverifiable',reason:'provider_outcome_ambiguous'})}await this.repository.markReported(scope,id,report.providerMessageId);return this.reconcile(scope,id,claimed.idempotencyKey)}
 async reconcile(scope:OwnerSendScope,id:string,idempotencyKey?:string):Promise<OwnerSendRequest>{const provider='providerForUser' in this.provider?this.provider.providerForUser(scope.subjectId):this.provider;const current=await this.repository.detail(scope,id);if(!['sending','unverifiable'].includes(current.state))return current;const key=idempotencyKey??`send-request:${current.id}:${current.draftId}:${String(current.draftVersion)}`;let status:ProviderSendStatus;try{status=await provider.status(key)}catch{return this.repository.finish(scope,id,{kind:'unverifiable',reason:'readback_unavailable'})}if(status.state==='verified')return this.repository.finish(scope,id,{kind:'verified',providerMessageId:status.providerMessageId,observedAt:status.observedAt,evidenceDigest:digest(status)});if(status.state==='rejected')return this.repository.finish(scope,id,{kind:'failed',reason:reasonCode(status.reasonCode)});return this.repository.finish(scope,id,{kind:'unverifiable',reason:`readback_${status.state}`})}
 private fresh(scope:OwnerSendScope){const at=scope.freshAuthAt?Date.parse(scope.freshAuthAt):NaN,now=this.now().getTime();if(!Number.isFinite(at)||now-at>FRESH||at>now+60_000)throw new SendRequestFreshAuthError()}
}
