import { reviseMailboxManagerAssignment, type MailboxManager } from '@hypermail/contracts';
import type { SqlClient } from '@hypermail/db';
import type { AgentConnectionsRepository, ConnectionState, ManagerChoice, ManagerSettingsView } from './contracts.js';
const columns=(m:ManagerChoice):[string,string|null]=>m.kind==='agent_connection'?[m.kind,m.connectionId]:[m.kind,null];
const date=(v:unknown)=>v instanceof Date?v.toISOString():String(v);
export class PostgresAgentConnectionsRepository implements AgentConnectionsRepository {
 constructor(private readonly sql:SqlClient){}
 async activateAssistant(userId:string,mailboxId:string,expectedAssignmentRevision:number,expectedGrantRevision:number|null):Promise<void>{
  await this.sql.transaction(async sql=>{
   await sql.query(`select id from app.accounts where id=$1::uuid and user_id=$2::uuid for update`,[mailboxId,userId]);
   const assignments=await sql.query(`select * from app.mailbox_manager_assignments where user_id=$1::uuid and account_id=$2::uuid for update`,[userId,mailboxId]);
   const assignment=assignments.rows[0];if(!assignment||Number(assignment['revision'])!==expectedAssignmentRevision)throw new Error('stale');
   const grants=await sql.query(`select * from app.agent_capability_grants where user_id=$1::uuid and account_id=$2::uuid for update`,[userId,mailboxId]);
   const grant=grants.rows[0];if((grant?Number(grant['revision']):null)!==expectedGrantRevision)throw new Error('stale');
   if(grant&&grant['manager_kind']!=='mastra')await sql.query(`update app.agent_capability_grants set state='revoked',revision=revision+1,updated_at=now() where id=$1::uuid and state<>'revoked'`,[grant['id']]);
   if(assignment['manager_kind']!=='mastra'||assignment['automatic_processing_enabled']!==true){
    const manager:MailboxManager=assignment['manager_kind']==='agent_connection'?{kind:'agent_connection',connectionId:String(assignment['agent_connection_id'])}:assignment['manager_kind']==='none'?{kind:'none'}:{kind:'mastra'};
    const next=reviseMailboxManagerAssignment({id:String(assignment['id']),userId,mailboxId,manager,automaticProcessingEnabled:assignment['automatic_processing_enabled']===true,revision:expectedAssignmentRevision,createdAt:date(assignment['created_at']),updatedAt:date(assignment['updated_at'])},{manager:{kind:'mastra'},automaticProcessingEnabled:true},new Date().toISOString()).assignment;
    await sql.query(`update app.mailbox_manager_assignments set manager_kind='mastra',agent_connection_id=null,automatic_processing_enabled=true,revision=$2,updated_at=$3::timestamptz where id=$1::uuid`,[assignment['id'],next.revision,next.updatedAt]);
   }
   const capabilities=['mail.list','mail.search','mail.read','attachment.read','folder.list','mail.archive','mail.move','mail.trash_recoverable','draft.create','draft.edit'];
   const updated=await sql.query<{id:string;revision:number}>(`insert into app.agent_capability_grants(user_id,account_id,manager_kind,agent_connection_id,capabilities,invocation_modes,state,revision,approved_at)
    values($1::uuid,$2::uuid,'mastra',null,$3::text[],ARRAY['automatic','interactive'],'active',1,clock_timestamp())
    on conflict(user_id,account_id) do update set manager_kind='mastra',agent_connection_id=null,capabilities=excluded.capabilities,invocation_modes=excluded.invocation_modes,state='active',revision=app.agent_capability_grants.revision+1,approved_at=excluded.approved_at,updated_at=clock_timestamp() returning id,revision`,[userId,mailboxId,capabilities]);
   const approved=updated.rows[0];if(!approved)throw new Error('stale');
   await sql.query(`insert into app.capability_grant_reapproval_events(event_id,grant_id,grant_revision,approver_user_id,approved_at) values($1,$2::uuid,$3,$4::uuid,clock_timestamp())`,[`assistant-activation:${approved.id}:${String(approved.revision)}`,approved.id,approved.revision,userId]);
   await sql.query(`insert into app.audits(actor_type,actor_id,account_id,event,correlation_id,metadata) values('user',$1,$2::uuid,'agent.assistant_activated',$3,$4::jsonb)`,[userId,mailboxId,`assistant-activation:${approved.id}:${String(approved.revision)}`,{capabilities,ownerConfirmed:true}]);
  });
 }
 async read(userId:string):Promise<ManagerSettingsView>{
  const [p,c,m]=await Promise.all([
   this.sql.query(`select default_manager_kind,default_agent_connection_id,revision from app.user_agent_preferences where user_id=$1::uuid`,[userId]),
   this.sql.query(`select id,adapter,display_name,state,lifecycle_revision,verified_at from app.agent_connections where user_id=$1::uuid order by created_at,id`,[userId]),
   this.sql.query(`select a.account_id,coalesce(ac.display_name,ac.email,a.account_id::text) mailbox_label,a.manager_kind,a.agent_connection_id,a.automatic_processing_enabled,a.revision assignment_revision,g.id grant_id,g.state grant_state,g.revision grant_revision,g.capabilities,g.invocation_modes from app.mailbox_manager_assignments a join app.accounts ac on ac.id=a.account_id left join app.agent_capability_grants g on g.user_id=a.user_id and g.account_id=a.account_id where a.user_id=$1::uuid order by mailbox_label,a.account_id`,[userId]),
  ]);
  const manager=(kind:unknown,id:unknown):ManagerChoice=>kind==='agent_connection'?{kind:'agent_connection',connectionId:String(id)}:kind==='none'?{kind:'none'}:{kind:'mastra'};
  const pref=p.rows[0];
  return {onboardingRequired:!pref,defaultManager:pref?{manager:manager(pref['default_manager_kind'],pref['default_agent_connection_id']),revision:Number(pref['revision'])}:null,
   connections:c.rows.map(r=>({id:String(r['id']),adapter:String(r['adapter']),displayName:String(r['display_name']),state:r['state'] as ConnectionState,lifecycleRevision:Number(r['lifecycle_revision']),verifiedAt:date(r['verified_at'])})),
   mailboxes:m.rows.map(r=>({mailboxId:String(r['account_id']),mailboxLabel:String(r['mailbox_label']),assignment:{manager:manager(r['manager_kind'],r['agent_connection_id']),automaticProcessingEnabled:r['automatic_processing_enabled']===true,revision:Number(r['assignment_revision'])},grant:r['grant_id']?{id:typeof r['grant_id']==='string'?r['grant_id']:'',state:r['grant_state'] as 'active'|'revoked'|'reapproval_required',revision:Number(r['grant_revision']),capabilities:r['capabilities'] as string[],invocationModes:r['invocation_modes'] as ('interactive'|'automatic')[]}:null}))};
 }
 async setDefault(userId:string,m:ManagerChoice,expectedRevision:number){const [kind,id]=columns(m);const r=await this.sql.query(`update app.user_agent_preferences set default_manager_kind=$3::app.mailbox_manager_kind,default_agent_connection_id=$4::uuid,revision=revision+1,updated_at=now() where user_id=$1::uuid and revision=$2 and (default_manager_kind,default_agent_connection_id) is distinct from ($3::app.mailbox_manager_kind,$4::uuid) returning revision`,[userId,expectedRevision,kind,id]);if(!r.rows[0])throw new Error('stale');}
 async setLifecycle(userId:string,connectionId:string,state:ConnectionState,expectedRevision:number){const r=await this.sql.query(`update app.agent_connections set state=$4::app.agent_connection_state,lifecycle_revision=lifecycle_revision+1,updated_at=now() where user_id=$1::uuid and id=$2::uuid and lifecycle_revision=$3 and state is distinct from $4::app.agent_connection_state and state <> 'security_revoked' returning lifecycle_revision`,[userId,connectionId,expectedRevision,state]);if(!r.rows[0])throw new Error('stale');}
 async setAssignment(userId:string,mailboxId:string,m:ManagerChoice,automatic:boolean,expectedAssignmentRevision:number,expectedGrantRevision?:number){const [kind,id]=columns(m);await this.sql.transaction(async sql=>{const current=await sql.query(`select manager_kind,agent_connection_id from app.mailbox_manager_assignments where user_id=$1::uuid and account_id=$2::uuid and revision=$3 for update`,[userId,mailboxId,expectedAssignmentRevision]);const row=current.rows[0];if(!row)throw new Error('stale');const managerChanged=row['manager_kind']!==kind||(row['agent_connection_id']??null)!==id;const a=await sql.query(`update app.mailbox_manager_assignments set manager_kind=$4::app.mailbox_manager_kind,agent_connection_id=$5::uuid,automatic_processing_enabled=case when (manager_kind,agent_connection_id) is distinct from ($4::app.mailbox_manager_kind,$5::uuid) then false else $6 end,revision=revision+1,updated_at=now() where user_id=$1::uuid and account_id=$2::uuid and revision=$3 and (manager_kind,agent_connection_id,automatic_processing_enabled) is distinct from ($4::app.mailbox_manager_kind,$5::uuid,$6::boolean) returning revision`,[userId,mailboxId,expectedAssignmentRevision,kind,id,automatic]);if(!a.rows[0])throw new Error('stale');if(managerChanged&&expectedGrantRevision!==undefined){const g=await sql.query(`update app.agent_capability_grants set manager_kind=case when $4='none' then manager_kind else $4::app.mailbox_manager_kind end,agent_connection_id=case when $4='none' then agent_connection_id else $5::uuid end,state=case when $4='none' then 'revoked'::app.capability_grant_state else 'reapproval_required'::app.capability_grant_state end,revision=revision+1,updated_at=now() where user_id=$1::uuid and account_id=$2::uuid and revision=$3 returning revision`,[userId,mailboxId,expectedGrantRevision,kind,id]);if(!g.rows[0])throw new Error('stale');}});}
 async reapproveGrant(userId:string,mailboxId:string,expectedGrantRevision:number,eventId:string,approvedAt:string){await this.sql.transaction(async sql=>{const g=await sql.query<{id:string;revision:number}>(`update app.agent_capability_grants set state='active',approved_at=$4::timestamptz,revision=revision+1,updated_at=now() where user_id=$1::uuid and account_id=$2::uuid and revision=$3 and state='reapproval_required' returning id,revision`,[userId,mailboxId,expectedGrantRevision,approvedAt]);if(!g.rows[0])throw new Error('stale');await sql.query(`insert into app.capability_grant_reapproval_events(event_id,grant_id,grant_revision,approver_user_id,approved_at) values($1,$2::uuid,$3,$4::uuid,$5::timestamptz)`,[eventId,g.rows[0].id,g.rows[0].revision,userId,approvedAt]);});}
}
