import type { SqlClient } from '@hypermail/db';
import type { AgentConnectionsRepository, ConnectionState, ManagerChoice, ManagerSettingsView } from './contracts.js';
const columns=(m:ManagerChoice):[string,string|null]=>m.kind==='agent_connection'?[m.kind,m.connectionId]:[m.kind,null];
/** Capabilities a fresh grant requests before owner approval; the safety ceiling still bounds every use. */
const INITIAL_GRANT_CAPABILITIES=['mail.read','mail.archive','mail.trash_recoverable','mail.move','mail.mark_read','mail.mark_unread','draft.create','draft.edit'];
const INITIAL_GRANT_MODES=['automatic'];
/** Authority arrived after arrival-time work was refused; clear the delivered queue marker so outbox recovery re-offers the job. */
const redispatchUnavailableJobs=(sql:SqlClient,mailboxId:string):void=>{void sql.query(`update app.agent_jobs j set queue_job_id=null, unavailable_reason=null, updated_at=now() from app.activities a where a.id=j.activity_id and a.account_id=$1::uuid and j.state='pending' and j.unavailable_reason is not null`,[mailboxId]);};
const date=(v:unknown)=>v instanceof Date?v.toISOString():String(v);
export class PostgresAgentConnectionsRepository implements AgentConnectionsRepository {
 constructor(private readonly sql:SqlClient){}
 async read(userId:string):Promise<ManagerSettingsView>{
  const [p,c,m]=await Promise.all([
   this.sql.query(`select default_manager_kind,default_agent_connection_id,revision from app.user_agent_preferences where user_id=$1::uuid`,[userId]),
   this.sql.query(`select id,adapter,display_name,state,lifecycle_revision,verified_at from app.agent_connections where user_id=$1::uuid order by created_at,id`,[userId]),
   this.sql.query(`select a.account_id,coalesce(ac.display_name,ac.email,a.account_id::text) mailbox_label,a.manager_kind,a.agent_connection_id,a.automatic_processing_enabled,a.revision assignment_revision,g.id grant_id,g.state grant_state,g.revision grant_revision,g.capabilities,g.invocation_modes from app.mailbox_manager_assignments a join app.accounts ac on ac.id=a.account_id left join app.agent_capability_grants g on g.user_id=a.user_id and g.account_id=a.account_id where a.user_id=$1::uuid order by mailbox_label,a.account_id`,[userId]),
  ]);
  const manager=(kind:unknown,id:unknown):ManagerChoice=>kind==='agent_connection'?{kind:'agent_connection',connectionId:String(id)}:kind==='none'?{kind:'none'}:{kind:'mastra'};
  const pref=p.rows[0];
  return {onboardingRequired:!pref,defaultManager:pref?{manager:manager(pref['default_manager_kind'],pref['default_agent_connection_id']),revision:Number(pref['revision'])}:null,
   connections:c.rows.map(r=>({id:String(r['id']),adapter:String(r['adapter']),displayName:String(r['display_name']),state:r['state'] as ConnectionState,lifecycleRevision:Number(r['lifecycle_revision']),verifiedAt:date(r['verified_at'])})),
   mailboxes:m.rows.map(r=>({mailboxId:String(r['account_id']),mailboxLabel:String(r['mailbox_label']),assignment:{manager:manager(r['manager_kind'],r['agent_connection_id']),automaticProcessingEnabled:r['automatic_processing_enabled']===true,revision:Number(r['assignment_revision'])},grant:r['grant_id']?{id:typeof r['grant_id']==='string'?r['grant_id']:'',state:r['grant_state'] as 'active'|'revoked'|'reapproval_required',revision:Number(r['grant_revision']),capabilities:r['capabilities'] as string[],invocationModes:r['invocation_modes'] as ('interactive'|'automatic')[]}:null}))};
 }
 async setDefault(userId:string,m:ManagerChoice,expectedRevision:number){const [kind,id]=columns(m);const r=await this.sql.query(`update app.user_agent_preferences set default_manager_kind=$3::app.mailbox_manager_kind,default_agent_connection_id=$4::uuid,revision=revision+1,updated_at=now() where user_id=$1::uuid and revision=$2 and (default_manager_kind,default_agent_connection_id) is distinct from ($3::app.mailbox_manager_kind,$4::uuid) returning revision`,[userId,expectedRevision,kind,id]);if(!r.rows[0])throw new Error('stale');}
 async setLifecycle(userId:string,connectionId:string,state:ConnectionState,expectedRevision:number){const r=await this.sql.query(`update app.agent_connections set state=$4::app.agent_connection_state,lifecycle_revision=lifecycle_revision+1,updated_at=now() where user_id=$1::uuid and id=$2::uuid and lifecycle_revision=$3 and state is distinct from $4::app.agent_connection_state and state <> 'security_revoked' returning lifecycle_revision`,[userId,connectionId,expectedRevision,state]);if(!r.rows[0])throw new Error('stale');}
 async setAssignment(userId:string,mailboxId:string,m:ManagerChoice,automatic:boolean,expectedAssignmentRevision:number,expectedGrantRevision?:number){const [kind,id]=columns(m);await this.sql.transaction(async sql=>{const current=await sql.query(`select manager_kind,agent_connection_id from app.mailbox_manager_assignments where user_id=$1::uuid and account_id=$2::uuid and revision=$3 for update`,[userId,mailboxId,expectedAssignmentRevision]);const row=current.rows[0];if(!row)throw new Error('stale');if(kind!=='none'){const existing=await sql.query(`select id from app.agent_capability_grants where user_id=$1::uuid and account_id=$2::uuid limit 1`,[userId,mailboxId]);if(!existing.rows[0])await sql.query(`insert into app.agent_capability_grants (user_id,account_id,manager_kind,agent_connection_id,capabilities,invocation_modes,state,revision,approved_at) values ($1::uuid,$2::uuid,$3::app.mailbox_manager_kind,$4::uuid,$5::text[],$6::text[],'reapproval_required',1,now())`,[userId,mailboxId,kind,id,INITIAL_GRANT_CAPABILITIES,INITIAL_GRANT_MODES]);}const managerChanged=row['manager_kind']!==kind||(row['agent_connection_id']??null)!==id;const a=await sql.query(`update app.mailbox_manager_assignments set manager_kind=$4::app.mailbox_manager_kind,agent_connection_id=$5::uuid,automatic_processing_enabled=case when (manager_kind,agent_connection_id) is distinct from ($4::app.mailbox_manager_kind,$5::uuid) then false else $6 end,revision=revision+1,updated_at=now() where user_id=$1::uuid and account_id=$2::uuid and revision=$3 and (manager_kind,agent_connection_id,automatic_processing_enabled) is distinct from ($4::app.mailbox_manager_kind,$5::uuid,$6::boolean) returning revision`,[userId,mailboxId,expectedAssignmentRevision,kind,id,automatic]);if(!a.rows[0])throw new Error('stale');if(managerChanged&&expectedGrantRevision!==undefined){const g=await sql.query(`update app.agent_capability_grants set manager_kind=case when $4='none' then manager_kind else $4::app.mailbox_manager_kind end,agent_connection_id=case when $4='none' then agent_connection_id else $5::uuid end,state=case when $4='none' then 'revoked'::app.capability_grant_state else 'reapproval_required'::app.capability_grant_state end,revision=revision+1,updated_at=now() where user_id=$1::uuid and account_id=$2::uuid and revision=$3 returning revision`,[userId,mailboxId,expectedGrantRevision,kind,id]);if(!g.rows[0])throw new Error('stale');}});}
 async reapproveGrant(userId:string,mailboxId:string,expectedGrantRevision:number,eventId:string,approvedAt:string){await this.sql.transaction(async sql=>{const g=await sql.query<{id:string;revision:number}>(`update app.agent_capability_grants set state='active',approved_at=$4::timestamptz,revision=revision+1,updated_at=now() where user_id=$1::uuid and account_id=$2::uuid and revision=$3 and state='reapproval_required' returning id,revision`,[userId,mailboxId,expectedGrantRevision,approvedAt]);if(!g.rows[0])throw new Error('stale');await sql.query(`insert into app.capability_grant_reapproval_events(event_id,grant_id,grant_revision,approver_user_id,approved_at) values($1,$2::uuid,$3,$4::uuid,$5::timestamptz)`,[eventId,g.rows[0].id,g.rows[0].revision,userId,approvedAt]);redispatchUnavailableJobs(sql,mailboxId);});}
}
