import type { AgentConnectionsRepository, ConnectionState, ManagerChoice } from './contracts.js';
import { ManagerConflictError, ManagerInputError } from './contracts.js';
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const revision=(value:number)=>{if(!Number.isInteger(value)||value<1)throw new ManagerInputError('A positive expected revision is required.');};
const manager=(value:ManagerChoice)=>{if(value.kind==='agent_connection'&&!uuid.test(value.connectionId))throw new ManagerInputError('Invalid Agent Connection.');};
export class AgentConnectionsService {
 constructor(private readonly repository:AgentConnectionsRepository, private readonly now:()=>Date=()=>new Date()){}
 read(userId:string){if(!userId)throw new ManagerInputError('Authentication is required.');return this.repository.read(userId);}
 async setDefault(userId:string, choice:ManagerChoice, expectedRevision:number){manager(choice);revision(expectedRevision);if(choice.kind==='none')throw new ManagerInputError('The initial/default Manager must be Hypermail AI or an Agent Connection. None is only available per Mailbox.');await this.wrap(()=>this.repository.setDefault(userId,choice,expectedRevision));return this.read(userId);}
 async setLifecycle(userId:string,connectionId:string,state:ConnectionState,expectedRevision:number){if(!uuid.test(connectionId))throw new ManagerInputError('Invalid Agent Connection.');revision(expectedRevision);if(state==='security_revoked') throw new ManagerInputError('Security revoke uses the dedicated security-revoke operation.');await this.wrap(()=>this.repository.setLifecycle(userId,connectionId,state,expectedRevision));return this.read(userId);}
 async securityRevoke(userId:string,connectionId:string,expectedRevision:number){if(!uuid.test(connectionId))throw new ManagerInputError('Invalid Agent Connection.');revision(expectedRevision);await this.wrap(()=>this.repository.setLifecycle(userId,connectionId,'security_revoked',expectedRevision));return this.read(userId);}
 async setAssignment(userId:string,mailboxId:string,choice:ManagerChoice,automatic:boolean,expectedAssignmentRevision:number,expectedGrantRevision?:number){if(!uuid.test(mailboxId))throw new ManagerInputError('Invalid Mailbox.');manager(choice);revision(expectedAssignmentRevision);if(choice.kind!=='none'&&expectedGrantRevision!==undefined)revision(expectedGrantRevision);await this.wrap(()=>this.repository.setAssignment(userId,mailboxId,choice,automatic,expectedAssignmentRevision,expectedGrantRevision));return this.read(userId);}
 async reapprove(userId:string,mailboxId:string,expectedGrantRevision:number,idempotencyKey:string){if(!uuid.test(mailboxId)||idempotencyKey.length<8||idempotencyKey.length>200)throw new ManagerInputError('Invalid grant approval.');revision(expectedGrantRevision);await this.wrap(()=>this.repository.reapproveGrant(userId,mailboxId,expectedGrantRevision,idempotencyKey,this.now().toISOString()));return this.read(userId);}
 private async wrap(work:()=>Promise<void>){try{await work();}catch(error){if(error instanceof ManagerInputError)throw error;throw new ManagerConflictError('Settings changed elsewhere. Reload before trying again.');}}
}
